### ISSUE TITLE
CMake 3.6.2

### ISSUE THREAD

**Issue by jibsen** [appveyor/ci#1001]
Could you update CMake to the 3.6.x series? It [adds support](https://cmake.org/cmake/help/v3.6/release/3.6.html) for the new Clang/C2 toolset in MSVC.

**Comment by jrfonseca** [comment]
FWIW, https://ci.appveyor.com/project/jrfonseca/drmingw started to fail when CMake was upgraded from 3.5.2 to 3.6.2, and it's building again now:

* https://ci.appveyor.com/project/jrfonseca/drmingw/build/134 pass (CMake 3.5.2)
* https://ci.appveyor.com/project/jrfonseca/drmingw/build/135 fail (CMake 3.6.2)
* https://ci.appveyor.com/project/jrfonseca/drmingw/build/137 pass (CMake 3.5.2)

I see from https://appveyor.tenderapp.com/discussions/problems/5262-build-become-invalid-with-no-changes-at-all that you reverted the images.

Comparing the logs, I only see two differences:

* CMake version 3.5.2 -> 3.6.2
* the case of `c:\projects` (`C:\projects` -> `C:\Projects`

I'm not sure exactly what was the problem: if the newer CMake version became sensitive to the case of `C:\projects`, or whether the new image had `Projects` instead of `projects` by mistake.

**Comment by FeodorFitsner** [comment]
We've rolled back the images for now, but 3.6.2 will return back when they are fixed.

You can troubleshoot with 3.6.2 now by using the following script to install it:

```
$cmakeUninstallPath = "${env:ProgramFiles(x86)}\CMake\Uninstall.exe"
if([IO.File]::Exists($cmakeUninstallPath)) {
    Write-Host "Uninstalling previous CMake ..." -ForegroundColor Cyan
    # uninstall existent
    "`"$cmakeUninstallPath`" /S" | out-file ".\uninstall-cmake.cmd" -Encoding ASCII
    & .\uninstall-cmake.cmd
    del .\uninstall-cmake.cmd
    Start-Sleep -s 10
}

Write-Host "Installing CMake 3.6.2 ..." -ForegroundColor Cyan
$msiPath = "$($env:USERPROFILE)\cmake-3.6.2-win32-x86.msi"

Write-Host "Downloading..."
(New-Object Net.WebClient).DownloadFile('https://cmake.org/files/v3.6/cmake-3.6.2-win32-x86.msi', $msiPath)

Write-Host "Installing..."
cmd /c start /wait msiexec /i $msiPath /quiet
del $msiPath

Add-Path 'C:\Program Files (x86)\CMake\bin'

remove-path 'C:\ProgramData\chocolatey\bin'
add-path 'C:\ProgramData\chocolatey\bin'

Write-Host "CMake 3.6.2 installed" -ForegroundColor Green
```

**Comment by jrfonseca** [comment]
@FeodorFitsner, thanks for the tip.  I tried what you suggested, but surprisingly it works fine:

https://ci.appveyor.com/project/jrfonseca/drmingw/build/job/547gma9u6qxufpb9

(On hindsight, I didn't managed to repro the build falure issue with CMake 3.6.2 neither when I tried on my systems.)

That is, it seems that whatever in the new image that caused my project's build to fail was not the CMake upgrade itself.

As I said, the only other noticeable difference with the new image was that some of the mentions to `C:\projects` in the log started to appear as `C:\Projects`, ie., upper case initial.  This does not happen with my CMake 3.6.2 sucessful build.  

Windows path are case insensitive, but many software derived from Unix might not.  Perhaps that was the root cause, and if it problems to CMake/Make then maybe there's some sort of validation script that can be run to ensure that `c:\projects` is not renamed as `C:\Projects`, nor that it's not referred like that in scripts / env vars, etc.

**Comment by FeodorFitsner** [comment]
Can you please point me to a place where `C:\Projects` mentioned?

**Comment by FeodorFitsner** [comment]
I'm running it  on the new image: https://ci.appveyor.com/project/FeodorFitsner/drmingw/build/2

Is there any way to understand/troubleshoot what's failing on an updated image? Is there a more detailed log or something?

**Comment by jrfonseca** [comment]
I just noticed, it actually appears as `C:/Projects`  for example, in your build and https://ci.appveyor.com/project/jrfonseca/drmingw/build/135/job/o78y4410g5u1f9ux shows

    Check for working C compiler: C:/Projects/drmingw/mingw64/bin/gcc.exe

where as in https://ci.appveyor.com/project/jrfonseca/drmingw/build/134/job/y64ljs57qlbvtv43 it showed

    Check for working C compiler: C:/projects/drmingw/mingw64/bin/gcc.exe

I only spotted this because I dowloaded the complete logs of the last passing / first failing build to my disk, removed the time stamps, and compared with a side-by-side diff tool.

And as you can see my successful CMake 3.6.2 build on https://ci.appveyor.com/project/jrfonseca/drmingw/build/139/job/547gma9u6qxufpb9 also shows `C:/projects` and not `C:/Projects`.

I suspect that either the dir was rename to Projects, or the environment is doing `cd C:\Projects` or soemthing like that.

**Comment by FeodorFitsner** [comment]
You were absolutely right! `C:\Projects` was the key - the empty folder was left on the image but should be entirely created during the build.

It works now: https://ci.appveyor.com/project/FeodorFitsner/drmingw/build/5

Thank you very much for helping to nail this nasty issue! :)

**Comment by jrfonseca** [comment]
Cool!  I'm glad I was of some assistance and you got to the bottom of this!
