### ISSUE TITLE
io.js support on build workers

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#113]

**Comment by am11** [comment]
:+1: 

I would vote for incorporating [nvmw](https://github.com/hakobera/nvmw/) in your environment. Since nvmw has about to get io.js support as well (see https://github.com/hakobera/nvmw/pull/36), it will be very helpful for you to switch platform and versions (while keeping the processes' workspace isolated).

**Comment by FeodorFitsner** [comment]
Support for io.js has been already added. It's like the same cmdlets, but if you request version `1.x` io.js will be installed.

**Comment by FeodorFitsner** [comment]
I'm currently working on KB article.

**Comment by FeodorFitsner** [comment]
Node.js and io.js guide has been published: http://www.appveyor.com/docs/lang/nodejs-iojs

Let us know what you think, what can be changed/added.

**Comment by am11** [comment]
Great thanks! :tada:

**Comment by FeodorFitsner** [comment]
The latest io.js 1.0.3 has been deployed to build workers.
