### ISSUE TITLE
Input line too long

### ISSUE THREAD

**Issue by GandaG** [appveyor/ci#1147]
Build: https://ci.appveyor.com/project/GandaG/relinker/build/32

After trying to activate a miniconda environment a "The input line is too long." error occurred.

**Comment by IlyaFinkelshteyn** [comment]
Hi Daniel,

This is because `path` environment variable is too long. It is that long because we need to support a lot of scenarios out-of-the-box.  You can make it shorter with PowerShell command like this:

`$env:path = ($env:path -split ";").Where({!($_ -like "*nunit*")}) -join ";"`

Note that in this example I get rid of all `path` entries which contain `nunit` just as example. You need to examine `path` yourself and decide what you can safely remove, then modify this command and run it before your activation script.

--ilya.

**Comment by GandaG** [comment]
Well, I didn't know where to prune so I just re-set the path to what I needed only :D
Thanks!
