### ISSUE TITLE
Windows 10 Image Support (for Universal Windows Driver testing)

### ISSUE THREAD

**Issue by nibanks** [appveyor/ci#1167]
What would be required to add Windows 10 image support? 

We (Microsoft) contribute to the [OpenThread](https://github.com/openthread/openthread) project and have recently added appveyor support for it. We encountered an issue with deploying the universal Windows driver though because it's running Windows 10. I found #439 which mentioned it might be added in the future, but it was closed over a year ago. Would it be possible to add Windows 10 to the list of possible images to use?

**Comment by FeodorFitsner** [comment]
We can't provide Windows 10 on AppVeyor because of its licensing restrictions, however we are going to offer Windows Server 2016 soon (not sure though if that works for UWP stuff). Otherwise there is a new feature called "private build clouds" which is currently in testing that allows customers to run builds on their own VMs in Azure, GCE, Amazon clouds. Azure has Windows 10 images, so it would be possible there.

**Comment by nibanks** [comment]
I believe Windows Server 2016 would work well enough for the universal driver testing. Do you have an ETA for that to be released?

**Comment by FeodorFitsner** [comment]
We are working with our hosting provider to make it available by the end of November, but not exact ETA yet.
