### ISSUE TITLE
Eliminate duplication in PSModulePath environment variable 

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1193]
Fix script:

```posh
$psModulePath = [System.Environment]::GetEnvironmentVariable('PSModulePath', 'Machine')
$psModulePath = ($psModulePath -split ';' | %{$_.Trim('\\')} | Select-Object -Unique) -join ';'
[Environment]::SetEnvironmentVariable('PSModulePath', $psModulePath, 'Machine')
```

**Comment by IlyaFinkelshteyn** [comment]
This was proposed solution:
$env:PSModulePath = [System.String]::Join(";", ($env:PSModulePath -split ";"| Get-Unique))

Customer made somthing better with trimming slashes:
$env:PSModulePath = ($env:PSModulePath -split ';' | %{$_.Trim('\\')} | Select-Object -Unique) -join ';'

**Comment by splatteredbits** [comment]
This is impacting me. I have a PowerShell module that includes DSC resources. These tests include DSC `configuration` blocks. These blocks are parsed and validated *before* PowerShell actually runs them. Any modules used by the `configuration` block are auto-loaded.

Because of the duplicate paths PSModulePath, PowerShell gives an error about duplicate modules being installed and my tests fail.

Please remove the duplicate paths from the PSModulePath environment variable.
