### ISSUE TITLE
Synchronize Add/Update test results

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1236]

**Comment by onovotny** [comment]
I am one of the xUnit authors. I’ve been working on getting the AppVeyor test reporting working for the new CLI builds with the Preview4 tooling and I’m noticing some inconsistent results with a large test project.

Look a the result counts:
https://ci.appveyor.com/project/dotnetfoundation/rx-net-la3iv/build/4.0.0-dev.42.build.101

https://ci.appveyor.com/project/dotnetfoundation/rx-net-la3iv/build/4.0.0-dev.42.build.102

Same commit, just different numbers (and neither of them is the full amount reported by the runner itself).

With a small test project, it reports them all correctly:
https://ci.appveyor.com/project/onovotny/xunittestproject1-test/build/1.0.15

We are using the AppVeyor batch API to try to maximize throughput but have no idea if we’re hitting message size limits or if something else is going on.

The code that’s interacting with the API is here:
https://github.com/xunit/xunit/blob/master/src/xunit.runner.reporters/AppVeyorClient.cs

It’s essentially a single threaded loop that’s reading request and update messages. There doesn’t seem to room for that kind of inconsistency. When the test run is done, the WaitOne method is called, which waits for the queues to drain and then finishes.

Is there anything you can assist with helping track down on your end?

Should be pretty easy to repro too by cloning the Rx.NET repo and running the \Rx.NET\Source\build-new.ps1 script.

**Comment by onovotny** [comment]
I’m wondering if things are getting lost between add and update. For something like test results, it might be easier to treat an update as an Upsert. I.e, don’t distinguish between the two and just people post (to either put or post, I don’t care).

For correlating, I’d be okay with stamping a sequence number in the message so that you can throw out messages that might arrive out-of-order for some reason.

Also, it there may need to be away to distinguish tests outside of name. With multi-targeting builds, the same test may be executed on multiple platforms. For example, on .NET 4.6 and .NET Core 1.0. I would suggest adding a Platform element to the input and then make the tests unique on name + platform + testframework. If you also bake in sequence Id’s (just a long), then it’d make it easy to only take the latest value.

**Comment by onovotny** [comment]
Question though…if there’s two queues, what happens if I send them to you in parallel and you get the update before the add? Or if you have an update with two status in it (do you go in order there?) Seems like adding a sequence number (or timestamp) may eliminate any ambiguity?
