### ISSUE TITLE
wget progress is shown in each line in CI output

### ISSUE THREAD

**Issue by XhmikosR** [appveyor/ci#1287]
See this for example https://ci.appveyor.com/project/XhmikosR/lighthouse/build/92/job/5i1s4gvlcm38jnae#L57

**Comment by Rondom** [comment]
That's how wget-behaves if it is not running on a interactive terminal.
This is not something specific to AppVeyor. Read the wget-manpage for different options such as `--no-show-progress` or `--quiet` or `--progress=[preferred-style]`

**Comment by XhmikosR** [comment]
Well, the MSYS wget doesn't have --no-sho-progress IIRC.

**Comment by Rondom** [comment]
What I wanted to say is: What makes you think that this is an AppVeyor-problem?
As I said, if you would like a different progress-reporting you can influence this via command-line options. I suggested three possibilities, I am sure one of them if not all three of them will work.

**Comment by XhmikosR** [comment]
Because other programs obviously output the progress, yet this issue doesn't happen with them.

**Comment by Rondom** [comment]
As I said. Different programs behave differently. In my opinion there is nothing AppVeyor-specific here.
wget detects whether there is i a TTY/windows console and if there is none it uses the "dot" progress indicator instead of the "bar" progress. In the manpage you can read, how to force one or the other progress (`--progress=bar:force`) or disable it all together (see above).

Again, AppVeyor only displays whatever wget is outputting.
