### ISSUE TITLE
something got broken between 23feb and 28 feb

### ISSUE THREAD

**Issue by chipitsine** [appveyor/ci#1353]
good one: https://ci.appveyor.com/project/chipitsine/openvpn-gui/build/cygwin-14
bad one: https://ci.appveyor.com/project/mattock/openvpn-gui/build/cygwin-3

both builds are produced from identical code (I compared using "diff -u -r")
also, it is strange why does cygwin tries to check whether compiler produces executable files.
configure is run with --build != --host, so, due to configure code it is cross build, so, check for executable does not make sense

**Comment by IlyaFinkelshteyn** [comment]
First I suspected that this is because our build worker image updated, but I tried the same commit with previous image and it fails the same way. I think this is external dependency, specifically `mingw64-i686-gcc-core`.
[Good one version is 5.4.0-3](https://ci.appveyor.com/project/chipitsine/openvpn-gui/build/cygwin-14/job/8041u1bu3q1pkx7e#L30)
[Bad one version is 5.4.0-4](https://ci.appveyor.com/project/mattock/openvpn-gui/build/cygwin-3/job/5o6r3a8r0v5xmnfw#L30).

**Comment by chipitsine** [comment]
thank you !
I'll investigate myself
