### ISSUE TITLE
Better communication on build worker updates 

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1430]
We need a better way to inform people about the fact that new build worker image is deployed. Thus people can switch to "Previous" images as mitigation faster.

Possible options are:
- notify that build worker was updated in build log (warning) or/and in UI
- maybe we can add some logic which will check if build was green before update and failed after

**Comment by Diggsey** [comment]
The "Previous" images system is not a good mechanism, it creates a lot of churn:
- image updated
- build fails
- find cause of failure
- find relevant appveyor issue to make sure
- open PR to update appveyor script to use "Previous" image
- wait for tests to pass
- merge PR
- fix underlying issue
- open PR with fix and update appveyor images
- wait for tests to pass
- merge PR

Now we're back where we started with a load of irrelevant changes in our git history.

Here's how it should look:
- image updated
- open issue to update appveyor image to latest
- open PR to update image, and fix any breakages caused by failures
- merge PR

If you version your images, then this is possible, and we can just put the version number in our appveyor file. If you don't want to support older versions, that's fine - if the version requested is too old, just default to the latest version with a warning. This gives everyone one image update cycle to get their builds working on the new image.

**Comment by wsfulton** [comment]
An email list that allows users to voluntarily subscribe to image updates will be perfect; it'll allow users to subscribe just to image updates if they are interested in them. Of course an easy way to unsubscribe should also be available. The emails ought to just send out what is on https://www.appveyor.com/updates/.

**Comment by xt0rted** [comment]
It'd be nice if there was an rss feed for https://www.appveyor.com/updates/. I've added feeds for other services to slack so when updates are posted I get notified about them. This is the easiest way for me since slack is where notifications for everything else go.

**Comment by FeodorFitsner** [comment]
The problem in the past was mixing "company & product" updates with technical updates. Technical updates come more frequently and as a result annoyed people were unsubscribing from all mailing lists all together.

I think we'll bring back e-mail notifications for technical updates, but with these design changes:

1. There won't be pre-checked "Technical updates" on sign-in form, so customers can't accidentally subscribe to these frequent emails.
2. We'll move technical updates subscription settings from "Profile" page to "Notifications" page where we currently have build and deployment notifications. "Notifications" page is more technical-oriented.
3. We'll make technical update mailing lists more granular, such as (lists and their names are not final):

    - AppVeyor Cloud updates
    - AppVeyor Enterprise updates
    - Build images updates
    - Infrastructure updates (addition/removal of clouds, changes to IP addresses, cache, storage updates, etc.)

**Comment by wsfulton** [comment]
:thumbsup:

**Comment by FeodorFitsner** [comment]
We've reintroduced "AppVeyor Technical updates" mailing list. Existing customers can subscribe on https://ci.appveyor.com/profile page.

**Comment by xt0rted** [comment]
@FeodorFitsner I'm only seeing an option for `Company news and platform updates`

**Comment by FeodorFitsner** [comment]
It's not deployed yet. Will be deployed later today.
