### ISSUE TITLE
Intermittent EPERM issues using npm link

### ISSUE THREAD

**Issue by darrenscerri** [appveyor/ci#1437]
Am trying to resolve an issue with a build failing for https://github.com/facebookincubator/create-react-app for branch `0.9.x`. I've been trying to fix it on my fork https://github.com/darrenscerri/create-react-app.

The build fails nearly every time at the same place, but occasionally passes for the same commit.

<img width="1000" alt="screen shot 2017-03-23 at 11 50 44" src="https://cloud.githubusercontent.com/assets/729230/24244411/0aaf3874-0fbf-11e7-8d8b-3f8a404fc329.png">

Failure:
<img width="951" alt="screen shot 2017-03-23 at 11 52 11" src="https://cloud.githubusercontent.com/assets/729230/24244459/44162794-0fbf-11e7-8aa0-212ef1ec4aeb.png">

Pass:
<img width="947" alt="screen shot 2017-03-23 at 18 06 00" src="https://cloud.githubusercontent.com/assets/729230/24260181/6de8ca0c-0ff3-11e7-94aa-8232c076ec0f.png">

AppVeyor: https://ci.appveyor.com/project/darrenscerri/create-react-app

**Comment by FeodorFitsner** [comment]
Will take a look.

**Comment by FeodorFitsner** [comment]
Hi Darren,

I did some tests and got more or less consistent successful results on `Visual Studio 2017` image: https://ci.appveyor.com/project/FeodorFitsner/create-react-app/history

I'm not sure about the reason it works "better" on Visual Studio 2017 image - maybe because it's based on Windows Server 2016 and built-in antivirus (Windows Defender) is explicitly disabled there. Maybe it's because of some underlying improvements in Hyper-V hypervisor/drivers (VS 2017 VMs run on Windows Server 2016 DC).

Anyway, you can run on `Visual Studio 2017` for now to see if it works better.

**Comment by darrenscerri** [comment]
Tests are passing now! Thanks for the help Feodor, much appreciated!

**Comment by darrenscerri** [comment]
Unfortunately, the [build from my repo](https://ci.appveyor.com/project/darrenscerri/create-react-app/build/1.0.21) succeeded but the [pull request](https://ci.appveyor.com/project/Facebook/create-react-app/build/1.0.399) didn't. Noticed that the error is the same error in [one of your build](https://ci.appveyor.com/project/FeodorFitsner/create-react-app/build/1.0.24) while you were trying VS2017. Do you have an idea of what that might be?

**Comment by FeodorFitsner** [comment]
It might be something module-specific. In the most cases it's racing condition.
Try using retry - we have a special `appveyor-retry` script that can be used like `appveyor-retry npm install`.

**Comment by darrenscerri** [comment]
Ok closing this issue then. Thanks a lot!
