### ISSUE TITLE
WiX projects fails on Visual Studio 2017 image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#1481]
Discussion: http://help.appveyor.com/discussions/problems/6427-the-wix-toolset-v3-build-tools-must-be-installed-to-build-this-project

**Comment by solvingJ** [comment]
Still getting the following on 2017 image: 
```

C:\Users\appveyor\AppData\Local\Temp\1\go-msi894620803>candle LicenseAgreementDlg_HK.wxs WixUI_HK.wxs product.wxs 
'candle' is not recognized as an internal or external command, operable program or batch file.
```

**Comment by IlyaFinkelshteyn** [comment]
Please add `set path=c:\Program Files (x86)\WiX Toolset v3.11\bin;%path%` at `install` step or somewhere else before you start using WIX.

**Comment by solvingJ** [comment]
Yes i've done that already thanks.  I suppose the request here is to make that part of the image so that users don't have to know to do this manual step every time they want to use wix.  Is that a reasonable request?

**Comment by IlyaFinkelshteyn** [comment]
We are trying to keep the length of ever-growing `path` variable under control, and add only what is completely necessary, when number of issues with some path  reaches some threshold. This is because people (or installers) do any kind of things with this variable during their builds and the longer it is the more risk it become broken.

**Comment by solvingJ** [comment]
I respectfully disagree but do appreciate the response.

**Comment by solvingJ** [comment]
On second thought, this is not a good suggestion or solution, because modifying the PATH variable via SET command is notoriously error prone and subject to issues due to the inherent 1024 character truncation.  It's really not good.  

I realize now that this should be a feature request to give customers a native and safe way to append the PATH variable from .appveyor.yml.  It's trivial to create new environment variables, but modifying PATH is not.  Please consider adding a special section to appveyor.yml which safely adds to the PATH variable by using registry manipulation (the safer way).
