### ISSUE TITLE
Xamarin Android build failure: class file has wrong version 52.0, should be 50.0

### ISSUE THREAD

**Issue by xleon** [appveyor/ci#1486]
It seams to be a problem with latest versions of Xamarin Android not picking up the correct SDK: http://stackoverflow.com/questions/38011359/xamarin-upgrade-causes-class-file-has-wrong-version-52-0-should-be-50-0-error

Full log here: https://ci.appveyor.com/project/xleon/i18n-portable/build/1.0.81

**Comment by FeodorFitsner** [comment]
Is there any recommendation on how to fix that?

**Comment by FeodorFitsner** [comment]
Right, thank you!

**Comment by prajjwaldimri** [comment]
I am also getting this error in the builds too. I have been already using the JDK v1.8 so it is not related to the JDK issue in my case. You can check the build results here: https://ci.appveyor.com/project/prajjwaldimri/githubuwp
I will post updates if I could get it to work.

**Comment by NPadrutt** [comment]
I have a similar issue.

In the output this is printed:

bad class file: java\lang\Object.class(java\lang:Object.class)
  class file has wrong version 52.0, should be 50.0
  Please remove or make sure it appears in the correct subdirectory of the classpath.
  public final class R

But when I connect to the server and execute javac -version and java -version it tells me I'm on  java 1.8.0_121.

I'm on Android sdk 7.1.

**Comment by NPadrutt** [comment]
As an addition: I tried to rebuild the last commit of a tag created 2 weeks or so ago and who passed. But this time it failed. So it seems there changed something on the build image.

**Comment by FeodorFitsner** [comment]
Have you tried asking about the issue on Xamarin forums? It looks like regression on Xamarin side in the recent VS 2017 builds.

**Comment by NPadrutt** [comment]
Not yet. But since I can build it locally with the latest VS 2017 version and also the one before without any issue it's hard to point to something on xamarin.

Based on the error message in the output I assume that somewhere still is a java 1.7.55 version used.

**Comment by FeodorFitsner** [comment]
OK, do you have a public project/build reproducing this issue?

**Comment by NPadrutt** [comment]
Ah, yeah. Here is the link to the project: https://github.com/MoneyFox/MoneyFox

Sorry, should have posted this right with the first comment :)

**Comment by DaniloBarros** [comment]
I am having this same issue for the past 7 days. 

I tried to change the java path in the .yml and the project to meet the requirement of version 50.0, as specified on the environment variables in AppVeyor site, and also following the instructions posted here, but nothing worked.

I posted in Xamarin Forums referring this issue ([here is the link](http://help.appveyor.com/discussions/problems/6459-xamarin-pcl-every-build-is-failing-msbuild-cannot-access-javalangobject)), there are all the information I gathered and thought was useful.

**Comment by FeodorFitsner** [comment]
Can you drop a link to Xamarin Forum's post?

**Comment by FeodorFitsner** [comment]
@NPadrutt I'm getting [error APPX0502: File 'C:\projects\moneyfox\Src\MoneyFox.Windows\bin\x86\Debug\arm\MoneyFox.Windows\MoneyFox.Windows_2.6.89.0_language-de.appx' not found.](https://ci.appveyor.com/project/FeodorFitsner/moneyfox/build/2.6.9#L1264) - do you know what that mean?

**Comment by FeodorFitsner** [comment]
Looks like we've found the source of this issue and the solution.

AppVeyor build workers have multiple versions of JDK installed: 1.6, 1.7 and 1.8. Seems like Android builds are now looking for Java in some different way and select Java with minimal version, in our case 1.6. You can noticed in a "bad" build log that `C:\Program Files (x86)\Java\jdk1.6.0\\bin\javac.exe` was used during the build. That's why it "cannot" read java .class files compiled with more recent version.

In the past it was possible to "trick" Android builds by removing Java 1.6 keys from the Registry, but looks like now it just scans folders with JDKs installed. While RDPing into build worker I uninstalled JDK 1.6 and as a result javac.exe from JDK 1.7 was used during the build. Renaming/removing folders with JDK 1.6 and 1.7 also worked.

Setting `JAVA_HOME` or changing `PATH` environment variables wasn't forcing msbuild to use JDK 1.8, however, a hint was found in [this thread](https://social.msdn.microsoft.com/Forums/en-US/d75f3f61-4656-40e8-9180-22bb2f7f82ac/uwp-build-definition-failing-in-vsts-with-error-msbuild-javacexe-error-cannot-access?forum=TFService) - setting up `JavaSdkDirectory` msbuild property (or environment variable with the same name).

Finally, adding this to `appveyor.yml` makes Android builds working again:

```
environment:
  JavaSdkDirectory: C:\Program Files (x86)\Java\jdk1.8.0
```

@prajjwaldimri GitHubXamarin green build: https://ci.appveyor.com/project/FeodorFitsner/githubxamarin

@DaniloBarros 2017.1-Forum-Coordenadores-DEG green build: https://ci.appveyor.com/project/FeodorFitsner/2017-1-forum-coordenadores-deg

I guess most of developers have a single JDK installed on their machines, so the issue is not reproducible locally.

**Comment by DaniloBarros** [comment]
Thank you very much! This was a right on the spot solution. This solved the problem for the builds failing. 

Thank you very much for your time and detailed explanation.

**Comment by prajjwaldimri** [comment]
Thank you :+1: :1st_place_medal:

**Comment by NPadrutt** [comment]
@FeodorFitsner  thanks for you help and your explanation! :)

Maybe the new issue is related to this here: http://stackoverflow.com/questions/43246485/visual-studio-2017-and-windows-10-sdk-10-0-15063-scale-100-appx-not-found

Locally the work around worked for me and it should be fixed with an update of Visual Studio.
