### ISSUE TITLE
Do not parse .vdproj as XML

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1496]
[Discussion](http://help.appveyor.com/discussions/problems/6491-appveyors-msbuild-settings-result-in-a-vdproj-being-read-even-though-its-not-part-of-the-build)

**Comment by EckyZero** [comment]
This is affecting my build process as well. I've disabled the Installer project inside my Solution Configurations, but still AppVeyor is trying to build it. What's the work around while we wait on this feature?

**Comment by IlyaFinkelshteyn** [comment]
Will force it. @EckyZero do you have public repro bu any chance to the the fix?

**Comment by EckyZero** [comment]
Yes - https://github.com/EckyZero/WCFRest_WindowsService

I got the build to continue by adding this to my appveyor settings

"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe" WcfRestfulWithWindowsHostDemo.sln /build Release

I'd still like the Installer file (DemoInstaller) to build though because I wanted the .msi file it generates. Thanks for the quick turn around @IlyaFinkelshteyn

**Comment by IlyaFinkelshteyn** [comment]
Fix we can do quickly is to stop parsing it as XML and do not feed to `msbuild`. If you still need to build it, you will be needed to feed it to `devenv.exe` or `devenv.com` yourself with custom build or `after_build` script.

**Comment by IlyaFinkelshteyn** [comment]
Fixed. No exception will be thrown, build will continue with warning like `<project_name>.vdproj is not a valid MSBuild project. You probably have to create custom script based on 'devenv.com' to build it.`
