### ISSUE TITLE
Toggle timestamp labels on build results log

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#150]
Discussions: http://help.appveyor.com/discussions/suggestions/586-execution-time-during-build-output

**Comment by Rondom** [comment]
I like how the time is hidden by default, but one can still hover over the line number to see the times. Toggling might be useful though, but I noticed myself calculating times a lot.

Besides the absolute time of each line it would also be useful to see the time relative time to each build step i.e. if I have a build step that takes 10 seconds, it would be able to see the time this build step takes (10s) and the relative time [0, 10) for each line in the log.

**Comment by waynebrantley** [comment]
Had no idea you could float over it.  That is helpful, but it would be better to just be [2m 22s] beside the line number.   @FeodorFitsner This request is from two years ago.   Any progress?

**Comment by Rondom** [comment]
I think it would be even more useful if individual build steps could have an individual relative time indicator. I might find it interesting that compiling was finished after 5:23, but then I might be interested in the fact that the packaging of the installer (separate build-step) took 2:40, but the only information I get right now is that it finished at 8:03.

So I propose to somehow display both relative and absolute time (or switch between them), because both are useful.

**Comment by FeodorFitsner** [comment]
Duplicate of https://github.com/appveyor/ci/issues/601
