### ISSUE TITLE
Missing notifications in pull requests

### ISSUE THREAD

**Issue by am11** [appveyor/ci#157]
AppVeyor is not notifying on libsass PRs: https://github.com/sass/libsass/pulls.

Related discussion: https://github.com/sass/libsass/pull/805#issuecomment-68759434.

**Comment by FeodorFitsner** [comment]
We see a lot of `Error setting gitHub repository 'sass/libsass' status: Response status code does not indicate success: 404 (Not Found)` in AppVeyor logs which basically could mean either a) commit doesn't exist and b) GitHub account authorized in AppVeyor doesn't have permissions to create commit status in ` sass/libsass` repository (GH gives 404 instead of 403).

**Comment by am11** [comment]
In case it is `b)`, is there a way we can fix it by re-authorizing GH account on AppVeyor?

**Comment by FeodorFitsner** [comment]
Yes, provided GH account is able to create commit status in that repository.
