### ISSUE TITLE
Error C1108: unable to find DLL: 'vcmeta.dll'  (VS2017 image)

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1572]
[Discussion](http://help.appveyor.com/discussions/problems/6712-unable-to-build-uwp-project)

**Comment by jgilm** [comment]
I have worked through the request in the discussion to repair the VS 2017 installation before completing the build. I was able to get the build to **succeed** by repairing the VS 2017 installation before continuing the build. The steps I took were:

- Used build worker image "Visual Studio 2017"
- Added the block RDP pause code to the appveyor.yml file in `init:` section
- After pushing the commit, appveyor started the build and paused. I RDP'd into the VM.
- Ran the Visual Studio Installer, clicked Repair to the VS 2017 Community Edition install
- After about 30 minutes repairing, I continued the build
- Build succeeded.

In order to verify that the Repair was what fixed the build, I attempted to rebuild the same commit **without** repairing the VS 2017 installation. The re-build failed as expected.

So it appears that the VS 2017 install in the build worker image needs to be repaired similar to what is listed in https://developercommunity.visualstudio.com/content/problem/54387/vcmetadll-not-found-after-latest-update.html#

**Comment by FeodorFitsner** [comment]
Oh, wow. Thanks for your efforts investigating the issue. That's good to know it's a common issue.
We'll do VS 2017 repair and update the image shortly this week. Will let you know when it's done.

**Comment by FeodorFitsner** [comment]
We've deployed an updated image with VS 2017 repaired. Could you please test your build and let me know if it worked?

**Comment by jgilm** [comment]
It is working fine now. Thanks!

**Comment by FeodorFitsner** [comment]
Cool, thanks for the update!
