### ISSUE TITLE
Nuget 4.1.0

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1590]
Update script:

```posh
    $nugetDir = 'C:\Tools\NuGet'
    if(Test-Path 'C:\Tools\NuGet3') {
        $nugetDir = 'C:\Tools\NuGet3'
    }

    (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v4.1.0/nuget.exe', "$nugetDir\NuGet.exe")
    Write-Host "NuGet 4.1.0 installed"
```

**Comment by ferventcoder** [comment]
Would love to know where this has been done in NuGet.

**Comment by IlyaFinkelshteyn** [comment]
@ferventcoder this script is just temporary workaround until new build worker image with Nuget 4.1.0 deployed and this issue closed.

**Comment by ferventcoder** [comment]
I meant I'm running into this as well and can't figure out where NuGet folks told us of this change. Looking for the actual notes.

**Comment by ferventcoder** [comment]
Sorry, this is one of the only things coming up in search currently.

**Comment by FeodorFitsner** [comment]
Interesting, let me know what you'll find so far :)
We just noticed from downloads page.

**Comment by ferventcoder** [comment]
I found this from http://help.appveyor.com/discussions/problems/5665-nuget-version

**Comment by ferventcoder** [comment]
https://github.com/NuGet/NuGetGallery/issues/4083 - ended up filing this.

**Comment by ferventcoder** [comment]
https://github.com/NuGet/NuGetGallery/issues/4315#issuecomment-314184221

**Comment by dustinmoris** [comment]
This issue seems to be super old, but my build started to fail because of an outdated nuget client today.

This was my last successful push (scroll to the very bottom): https://ci.appveyor.com/project/dustinmoris/giraffe/build/0.1.0-beta-300-345
And this is what I got today: https://ci.appveyor.com/project/dustinmoris/giraffe/build/0.1.0-beta-310-359

I am getting now:
`NuGet account requires protocol version 4.1.0 - using NuGet command line tool`.

**Comment by ferventcoder** [comment]
I might recall a blog or email where they mentioned rolling the req out for all users.

**Comment by IlyaFinkelshteyn** [comment]
@dustinmoris `NuGet account requires protocol version 4.1.0 - using NuGet command line tool` is not error, it is information message that we use latest command line tool (instead of direct API call) to satisfy new requirements. Your actual error is `ERROR: Response status code does not indicate success: 409 (A package with ID 'Giraffe.DotLiquid' and version '0.1.0-beta-100' already exists and cannot be modified.)`. If you look at your successful build, you actually had the same [response from server](https://ci.appveyor.com/project/dustinmoris/giraffe/build/0.1.0-beta-300-345#L417). Difference is that when AppVeyor uses API it can detect this kind of response and skip upload. With command line it returns error. We are working to get rid of command line and use API directly again with new requirements. But I am not sure what is better behavior for you -- do you really need this `already exists` error to be skipped or it exposed some issue with nuget versioning in your build which you did not notice before?

**Comment by IlyaFinkelshteyn** [comment]
@ferventcoder FYI https://github.com/NuGet/Announcements/issues/10

**Comment by ferventcoder** [comment]
Thanks for that, I thought they had started requiring that. 👍

**Comment by dustinmoris** [comment]
@IlyaFinkelshteyn Yes I saw that the real error was from the web response, but as you said previously this did not fail my builds. I would prefer if it would not fail my build, because my project builds multiple NuGet packages, but all of them have been updated with each tagged build, so it is expected that some will get pushed and some will be ignored because they haven't changed.

**Comment by IlyaFinkelshteyn** [comment]
@dustinmoris Agreed, should be fixed soon, please watch https://github.com/appveyor/ci/issues/1845

**Comment by IlyaFinkelshteyn** [comment]
@dustinmoris It is fixed, please let us know if you hit any issues.
