### ISSUE TITLE
AppVeyor checks out a commit rather than a branch

### ISSUE THREAD

**Issue by thomaslevesque** [appveyor/ci#1606]
Apparently AppVeyor checks out a specific commit, rather than a branch, which puts the repo in "detached head" state. It usually doesn't matter, but causes issues for GitVersion. For instance, [this build](https://ci.appveyor.com/project/FakeItEasy/fakeiteasy/build/281) was built on the `release-3.4.0 branch`, but since it was built in detached head state, GitVersion didn't know that it was on a branch, so it produced a `3.4.0-alpha0069` version instead of `3.4.0-beta0001`.

**Comment by IlyaFinkelshteyn** [comment]
We have to do this to ensure we build specific commit, and not latest in the branch. But you can add `git checkout %APPVEYOR_REPO_BRANCH%` at the `install` stage.

**Comment by thomaslevesque** [comment]
Ah, I see, thanks. I guess I'll do that. Another option would be to checkout `%APPVEYOR_REPO_BRANCH%`, and reset it to `%APPVEYOR_REPO_COMMIT%`

**Comment by Ede123** [comment]
I faced this problem yesterday and have one question regarding `APPVEYOR_REPO_BRANCH`.

According to https://www.appveyor.com/docs/environment-variables/:
> `APPVEYOR_REPO_BRANCH` - build branch. For Pull Request commits it is base branch PR is merging into

If I understand this correctly it means that the variable will *not* hold the actual branch name for pull requests? If so is there an easy possibility to get the branch name rather than the name of the base branch?

I resorted to `git branch | tail -n 1 | tr -d ' '` which works, too, but seems a bit inelegant (especially given that AppVeyor should know the actual branch name).
