### ISSUE TITLE
deleted builds still show up on github's commit status

### ISSUE THREAD

**Issue by umlaeute** [appveyor/ci#1634]
Due to #1633 my github project has a number of PRs that show up with failing CI status.

In order to not upset the committers too much, I tried removing the builds from the appveyor page, hoping that this would make the PRs on GitHub automatically "CI-clean" again.

Unfortunately the result is, that the PRs on GH still show up with a failing CI check, but when I click on the "Details" button, this takes me to an AppVeyor page showing:
> Build not found or access denied.

I would have expected that the commit status on GitHub was updated to show "skipped" or similar.

This is one of the PRs in question https://github.com/pure-data/pure-data/pull/79#partial-pull-merging
The Details page takes me to this "error" page: https://ci.appveyor.com/project/umlaeute/pure-data/build/1.0.13

**Comment by IlyaFinkelshteyn** [comment]
We cannot do this manually because we cannot (and should not) do anything **manually** on your behalf. You can reset status to green with [Statuses API](https://developer.github.com/v3/repos/statuses/). Good curl example is [here](https://webapps.stackexchange.com/questions/78517/is-there-any-way-to-delete-pull-request-status-checks-on-github) (please not V3 API syntax).

**Comment by umlaeute** [comment]
thanks, this looks promising.
