### ISSUE TITLE
How to disable merge commit building

### ISSUE THREAD

**Issue by minggo** [appveyor/ci#1662]
appveyor will trigger a building after a PR is merged, but it is not needed since it passed the building when the PR is sent.

For example, [the first building](https://ci.appveyor.com/project/minggo/cocos2d-x/build/1.0.12) is triggered when the PR is sent to cocos2d-x, [the second building](https://ci.appveyor.com/project/minggo/cocos2d-x/build/1.0.14) is triggered when the PR is merged. And you can see [the build history](https://ci.appveyor.com/project/minggo/cocos2d-x/history), there are two jobs for `fix crash if there are more than 10 touches`.

**Comment by IlyaFinkelshteyn** [comment]
This is generally right thing to do, because some other feature branch can be merged into master, between initial virtual merge build and final actual merge build.
If you are sure you have only single feature branch at the time and find actual merge build useless, you can prevent it by adding `[skip ci]` to commit message when you do actual merge ([details](https://www.appveyor.com/docs/how-to/filtering-commits/#skip-directive-in-commit-message)).

**Comment by minggo** [comment]
Got it, thanks.
