### ISSUE TITLE
Avoid NuGet packaging duplication if 'GeneratePackageOnBuild' is set

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1764]
It seems that it can be set implicitly:
https://github.com/Microsoft/msbuild/issues/2495
http://help.appveyor.com/discussions/problems/7680-build-failing-currently-dotnet-pack-command-does-not-have-an-option-to-include-referenced-projects

**Comment by dasMulli** [comment]
You can always override the `GeneratePackageOnBuild` feature via a global property specified on the build (`/p:GeneratePackageOnBuild=true` as argument or a `GeneratePackageOnBuild` environment variable)

**Comment by dasMulli** [comment]
this will have precedence over any property that is set statically in the project

**Comment by IlyaFinkelshteyn** [comment]
@dasMulli In case `publish_nuget: true` set in YAML (or similar in UI), AppVeyor runs `dotnet pack` against "new" `.csproj` files and uploads nuget packages as artifact.

I was thinking about detecting `GeneratePackageOnBuild` in `.csproj` (and after your [comment](https://github.com/Microsoft/msbuild/issues/2495#issuecomment-326687462) in imports), and if it set to `true` prevent AppVeyor to do all this against certain `.csproj` file.

But maybe (only in case `publish_nuget: true` set in YAML) it would be safer (and faster) to just blindly set `GeneratePackageOnBuild` to `false` and let AppVeyor to do `dotnet pack` and nuget artifacts uploading. In this case f someone prefer nuget packaging behavior controlled by `.csproj`, it can be enabled by removing `publish_nuget: true` (or similar in UI). Does it feels user friendly?

**Comment by dasMulli** [comment]
And `publish_nuget` also controls publishing?

Another alternative would be to set  `GeneratePackageOnBuild` to true for a build invocation if you have that under control.. (and it should be faster doing it in one invocation for large projects)

worst case scenario is that the package would be built twice.

Correctly detecting a set property is hard, you'd essentially have to do a design-time build to correctly evaluate fancy expressions like
```xml
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))" />
```

Another input: When you're running on win boxes with a full VS 2015 installed, it may be safer to run `msbuild /t:Pack` instead of `dotnet pack` so that even projects relying on full msbuild can pack ([`Newtonsoft.Json`](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Newtonsoft.Json.csproj#L68-L84) sets a popular example for this)

**Comment by IlyaFinkelshteyn** [comment]
Yes, when `publish_nuget` is set to `true`, AppVeyor not only creates nuget package, but also packages it as artifact. When nuget artifact published (regardless how) AppVeyor also publishes it into project nuget feed.

Sure we do no build twice (true for both .NET core and "classic" .NET nuget packaging).

Automatic AppVeyor .NET Core nuget packaging works only with "new" `.csproj` files, which are not going to be built on `Visual Studio 2015` image anyway.

I think that we will just add `/p:GeneratePackageOnBuild=false` to `msbuild` command if `publish_nuget` is set to `true`. And if customer decide to rely on msbuild-integrated nuget packaging, and contol it with `.csproj` and custom artifact settings, then `publish_nuget` should be removed (or set to `false`).

@dasMulli thanks a lot for your input!

**Comment by IlyaFinkelshteyn** [comment]
Now we add `/p:GeneratePackageOnBuild=false` to `msbuild` command in case build configuration contains `publish_nuget: true` (or similar in UI). We assume that in case `publish_nuget: true` was set, it is expected that AppVeyor takes care of packaging, so we prevent duplicate work.
