### ISSUE TITLE
dotnet pack fails on a single project

### ISSUE THREAD

**Issue by bruno-garcia** [appveyor/ci#1767]
[Greentube.Monitoring](https://github.com/Greentube/monitoring/) project has 6 projects that result in nuget packages.

[All but Greentube.Monitoring.Redis are successfully packed.](https://ci.appveyor.com/project/Greentube/monitoring#L302)

Running `dotnet pack` locally (Windows 10 x64) works fine.

**Comment by IlyaFinkelshteyn** [comment]
I think that problem is the following:

 - `Greentube.Monitoring.Redis` targets both [netstandard1.3 and net46 frameworks](https://github.com/Greentube/monitoring/blob/master/src/Greentube.Monitoring.Redis/Greentube.Monitoring.Redis.csproj#L4)
- Build scenario assumes that `dotnet test` will implicitly build all referenced projects
- Apparently [Greentube.Monitoring.Redis.Tests](https://github.com/Greentube/monitoring/blob/master/test/Greentube.Monitoring.Redis.Tests/Greentube.Monitoring.Redis.Tests.csproj) does not require referenced assembly which built against .NET 4.6 (probably because it is .NET Core test), so it was not built.
- `nuget pack` (with `--no-build` option) [cannot find  .NET 4.6 assembly](https://ci.appveyor.com/project/Greentube/monitoring/build/1.1.15#L303) and fails.

Workaround I see is to skip `--no-build` option for problem project. Here is PowerShell sample to replace your `after_build` command (feel free implement the same in cmd `for` command, if you like it more):
```
- ps: Get-ChildItem .\src\ |  ForEach-Object {if ($_.name.Contains("Redis")){dotnet pack -c $env:Configuration src/$_/$_.csproj} else {dotnet pack --no-build -c $env:Configuration src/$_/$_.csproj}}
```

**Comment by bruno-garcia** [comment]
Thanks for spotting that! That package still targets a pre release version of SE.Redis so I will update that ref and target netstandard only.
