### ISSUE TITLE
CMake 3.9.4

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#1802]

**Comment by psavery** [comment]
This is the comment I made on the forums by the way about this:

Some parts of CMake do not work properly with Visual Studios 2017 - and they were fixed with CMake version 3.9.2.

I'm thinking of InstallRequiredSystemLibraries in particular. CMake cannot find and install the system libraries of the newest version of Visual Studios 2017 until CMake 3.9.2. It's a feature I personally need.

**Comment by chfast** [comment]
CMake 3.9.3 has another set of fixes for Visual Studio generator. Thanks for tracking this upgrade.
