### ISSUE TITLE
RDP gives 'invalid credentials'

### ISSUE THREAD

**Issue by jeroen** [appveyor/ci#1919]
I have set `APPVEYOR_RDP_PASSWORD` in [my repo](https://ci.appveyor.com/project/jeroen/base/history) settings. My RDP client can connect to the address that is printed by the script, however it fails to login with "invalid credentials".

I tried changing `APPVEYOR_RDP_PASSWORD` to something else, and I tried both an RDP client on MacOS and Windows, but for both I can't login with username `appveyor` and the set password. Is there something I am overlooking?

**Comment by jeroen** [comment]
It suddenly seems to work now. I have no idea what has changed.

**Comment by IlyaFinkelshteyn** [comment]
@jeroen please watch this issue https://github.com/appveyor/ci/issues/1906. If you use RDP often I would recommend do not use `APPVEYOR_RDP_PASSWORD` but rely on AppVeyor-generated one while this issue is open. Because until this fixed you can get into this issue randomly. Sorry for the trouble. We will try to fix it soon.
