### ISSUE TITLE
Encrypted variables are not decrypted when building a PR

### ISSUE THREAD

**Issue by joostvanhassel** [appveyor/ci#2044]
We use an encrypted variable to set the password of a Nuget source (which is an AppVeyor feed of an external organisation, therefore we add it ourselves):
`nuget sources add -Name OurSource -Source \"https://ci.appveyor.com/nuget/oursourcepath/\" -UserName \"%nuget_user%\" -Password \"%nuget_password%\"`

The variable `nuget_password` is marked as encrypted in the environment settings. This all works perfectly fine when building branches. However, when building a PR, the variable does not seem to be decrypted. When we don't mark the variable as encrypted, the build of the PR succeeds.

**Comment by IlyaFinkelshteyn** [comment]
Secure variables are not decoded in PRs for security reason (otherwise any person submitting a PR can print them). It is described [here](https://www.appveyor.com/docs/build-configuration/#secure-variables) in the documentation.
Private projects have UI only option `Enable secure variables in all Pull Requests`, public projects have `Enable secure variables in Pull Requests from the same repository only`. Both located in General settings tab.
