### ISSUE TITLE
Unable to fork in Msys2

### ISSUE THREAD

**Issue by pavelkryukov** [appveyor/ci#2154]
Hi

We experience random errors in forks occurred during msys64 builds today:
```
      1 [main] make 2196 fork: child -1 - forked process 3928 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
make[2]: fork: Resource temporarily unavailable
```

Examples:
https://ci.appveyor.com/project/miptilab/mipt-mips/branch/master/job/2qhqnwr2qmyg8ma4
https://ci.appveyor.com/project/miptilab/mipt-mips/branch/master/job/uhee74ex7hexa5dv

**Comment by IlyaFinkelshteyn** [comment]
@pavelkryukov this can be connected to recent [build worker images update](https://www.appveyor.com/updates/2018/03/12/) which includes MSYS2 updates.

As a temporary workaround please try to use `Previous Visual Studio 2017` image.

Let us know if this help, but even if yes, do not close the issue, we need to root cause and fix it (or have a workaround) it before next build worker image update (when current image becomes "Previous").

**Comment by pavelkryukov** [comment]
Thanks, it helps.

**Comment by pavelkryukov** [comment]
I can't reproduce it in the new image

**Comment by pavelkryukov** [comment]
I still see the failure in new image. Additionally, I noticed that it does not happen if "build" is set to "msvc", only "g++" builds are failing (we use MSys in both)

**Comment by pavelkryukov** [comment]
Fixed in the image of last week
