### ISSUE TITLE
Update emails working?

### ISSUE THREAD

**Issue by wsfulton** [appveyor/ci#2172]
My profile at https://ci.appveyor.com/profile has _Company news and platform updates_ as *Active*. I don't ever receive anything (I've checked my spam too). For example it would have been helpful to receive the technical update on March 12 as shown on https://www.appveyor.com/updates/ as the change broke our builds. Are these emails actually sent?

**Comment by IlyaFinkelshteyn** [comment]
@wsfulton you are correct that we need to communicate those things better. We are not sure about email because so many people become unhappy with frequent email so we use it only for major announcements.

I am closing this issue in favor of https://github.com/appveyor/ci/issues/1430. We will bump priority for it.
