### ISSUE TITLE
Accidental failures to login to SQL Server

### ISSUE THREAD

**Issue by morozov** [appveyor/ci#2204]
From time to time (e.g. [doctrine/dbal#1.0.47](https://ci.appveyor.com/project/doctrine/dbal/build/1.0.47/job/cnwvfxdh24s6neac), more can be added if needed), the following error appears in the build log:
> SQLSTATE [28000, 18456]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Login failed for user 'sa'.
> SQLSTATE [42000, 4060]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Cannot open database "doctrine_tests" requested by the login. The login failed.

I don't have any hard evidence that the problem is on the AppVeyor side but I see it only on AppVeyor (e.g. doesn't happen on [30+ different Travis CI configurations](https://travis-ci.org/doctrine/dbal/builds/358259919) including SQL Server on Linux).

**Comment by IlyaFinkelshteyn** [comment]
Given the fact that it is intermittent and that you [start SQL](https://github.com/doctrine/dbal/blob/b29ac665d3d20acf9abcf55db4a0fb08f6e9394d/.appveyor.yml#L95) right before tests, I would speculate that problem is that SQL is not completely started by the time test started (sometimes). `Start-Service` is asynchronous and returns before service actually started. Try to add waiting for service status to be `running` or simple use synchronous `net start` command. Or start it earlier (say at `install` stage. Let us know if this helps.

**Comment by IlyaFinkelshteyn** [comment]
@photodude I did not mention this because you can get too much jobs you do not need. You can [exclude](https://www.appveyor.com/docs/build-configuration/#exclude-configuration-from-the-matrix) them though.

**Comment by photodude** [comment]
@IlyaFinkelshteyn Just ran a test with the matrix service start and it hung on the first test at 4% in phpunit

https://ci.appveyor.com/project/photodude/dbal/build/1.0.305/job/brmknshwme5e1nlg

I put the services in the matrix so only one service should be starting with each of the builds in the matrix https://github.com/photodude/dbal/blob/patch-2/.appveyor.yml

**Comment by IlyaFinkelshteyn** [comment]
@photodude oh, sorry, `services` is not first class matrix dimension. Filed https://github.com/appveyor/ci/issues/2207 to make it work inside matrix. For now I believe try just `net start`  (or `Start-Service` with custom waiting)...
