### ISSUE TITLE
pwsh.exe should load AppVeyor module on start

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2513]
Fix:

```posh
$psDir = "$env:USERPROFILE\Documents\PowerShell"
if (-not (Test-Path $psDir)) {
    New-Item -ItemType Directory -Path $psDir -Force
}
$modulePath = "C:\Program Files\AppVeyor\BuildAgent\dotnetcore\AppVeyor.BuildAgent.PowerShell.dll"
$profileContent = "if (Test-Path `"$modulePath`") { Import-Module `"$modulePath`" }"
Set-Content -Path (Join-Path -Path $psDir -ChildPath 'Microsoft.PowerShell_profile.ps1') -Value $profileContent
```

**Comment by FeodorFitsner** [comment]
It's deployed now.

**Comment by JustArchi** [comment]
https://ci.appveyor.com/project/JustArchi/archisteamfarm/build/5510-master/job/y6h22891fv79ohe7#L398 😅

**Comment by FeodorFitsner** [comment]
OK, how do you call `pwsh.exe`?

**Comment by JustArchi** [comment]
My entire config is inside tree, so feel free to take a look - I call it in a normal way by using it for a build script, https://github.com/JustArchi/ArchiSteamFarm/blob/master/appveyor.yml

**Comment by FeodorFitsner** [comment]
so, you are not calling `pwsh.exe` directly, but only run with `- pwsh: ...`?

**Comment by JustArchi** [comment]
Yes, in fact, I just changed (previously used) `ps` for `pwsh`, didn't do any other changes as I didn't need them. In previous `ps` script I used `Push-AppveyorArtifact` and it worked properly, since switch to `pwsh` I had to rename `Push-AppveyorArtifact` into `appveyor PushArtifact` as the cmdlet was not recognized under `pwsh` (it was recognized in `ps`). I didn't have to do any other changes, but mainly because I didn't use any `ps` exclusive features that weren't available in `pwsh`. Thank you a loot for taking a look @FeodorFitsner
