### ISSUE TITLE
Latest Visual Studio 2017 breaks binding redirects.

### ISSUE THREAD

**Issue by JimBobSquarePants** [appveyor/ci#2519]
As of the last three days our AppVeyor tests have been failing against NetCore 2.1 with the following message.

```
System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
874
      ---- System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```
See https://ci.appveyor.com/project/six-labors/imagesharp/build/1.0.0-PullRequest00656001666/job/36pm890nu3ivdl5u

There have been no project or build configuration changes to trigger this.

Changing the image to `Previous Visual Studio 2017` fixes the issue.

https://ci.appveyor.com/project/six-labors/imagesharp/build/job/9q7e6cy8ggdfp379

**Comment by OwenMcDonnell** [comment]
I've been playing around with a fork of your project but so far all I can see is that previously, `dotnet restore` was logging installation of the mentioned assembly, and now on the broken builds it is not. So I haven't found a solution yet, but I'll keep searching.

Stick with the previous image for now (likely won't be replaced too soon) and I'll keep you updated as to my findings.

**Comment by OwenMcDonnell** [comment]
Since dotnet core [was updated to 2.1.2](https://www.appveyor.com/updates/2018/07/12/) the sdk got updated as well and so did the packages in the Nuget fallback folder. Therefore, the `dotnet restore` command already sees version 4.5.1 of  'System.Runtime.CompilerServices.Unsafe' and doesn't install it. 
...Though I can't really say why the `dotnet build` command is not taking the required binaries from that fallback folder :(

Anyways, you can add `/p:DisableImplicitNuGetFallbackFolder=true` to the end of [this line](https://github.com/SixLabors/ImageSharp/blob/master/build.ps1#L96) and that should cause the dependency to be installed to the packages folder where the build can pick it up.

**Comment by JimBobSquarePants** [comment]
Thanks for taking time to investigate this. I really appreciate it!

**Comment by OwenMcDonnell** [comment]
No problem.

**Comment by gregsdennis** [comment]
The "this line" link is bad now.  Can you specify the command that needs updating, please?
