### ISSUE TITLE
Visual Studio 2015 support in "MSBuild" scenario

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#257]
Discussion: http://help.appveyor.com/discussions/problems/2066-problem-building-with-vs-2015-release-candidate

**Comment by am11** [comment]
How do we lockdown or even know which version of VS will AppVeyor use in msbuild scenario? 

For instance, here is our AppVeyor configuration: https://github.com/sass/libsass/blob/master/appveyor.yml without specifying VS version. 

Since VS2015 supports most of the C++11/14/17, C99 and some C11 features, if the team decides to maintain less quirky, strict standard C/C++ code by locking down the CI builds and tests to VS2015:

* will AppVeyor CI jobs default to latest VS version 2015 coming Monday, when VS2015 is going RTM or default will remain set to VS2013?
* do we need to add the following key:

   ```yaml
   os: Visual Studio 2015
   ```
* or should we set environment variable:

  ```yaml
  environment:
    VisualStudioVersion: 14.0
  ```

**Comment by FeodorFitsner** [comment]
VS 2015 RC is already supported in two ways:

1) Select "Visual Studio 2015 RC" OS on Environment tab of specify "os: Visual Studio 2015 RC" in appveyor.yml. Custom images are getting built on Azure, so it's slow.
2) Switch your account to a new OSS environment which has VS 2015 RC installed by default. It's almost fast as Pro, but VMs have less power (see http://www.appveyor.com/docs/build-configuration#virtual-machine-configurations).

A new image with VS 2015 RTM (and OSS environment update) will be available tomorrow.

We are not deploying VS 2015 to Pro environment yet, as it can break many builds. We'll do a survey in a week or so to understand demand.
