### ISSUE TITLE
dotnet_csproj doesn't work?

### ISSUE THREAD

**Issue by HarelM** [appveyor/ci#2625]
I wanted to add the build version to the dlls I compile.
Here is the screenshot of the details on windows - no version
![image](https://user-images.githubusercontent.com/3269297/45385522-a8f70a00-b619-11e8-8543-dbfc61d1cec8.png)
build:
https://ci.appveyor.com/project/IsraelHikingHost/site/build/7.2.18
yml:
https://github.com/IsraelHikingMap/Site/blob/master/appveyor.yml
build artifacts can be downloaded and checked.
I'm probably missing something in my repo.
But the log doesn't have any patching error message, it doesn't tell how many dlls were patched too so I would suggest to improve the message this tool emits at least...

**Comment by IlyaFinkelshteyn** [comment]
Problem is discussed [here](https://github.com/appveyor/ci/issues/1907) with specific solution [here](https://github.com/appveyor/ci/issues/1907#issuecomment-342578875).

Side note: this is neither bug or feature request. As you see in templates when you created this, we are trying to keep support separately in the support forum.

**Comment by HarelM** [comment]
The feature request is there:
>But the log doesn't have any patching error message, it doesn't tell how many dlls were patched too so I would suggest to improve the message this tool emits at least...

Saying how many dlls were affected by this would improve a lot - I wouldn't need to wait for the build to end, download the files and see that this didn't happen...

**Comment by IlyaFinkelshteyn** [comment]
It tells what project is patched when patching happens  (`*.csproj` contains `Version` property with any value). It does not tell anything about projects, for which patching was skipped. 

I am not sure we have to list each skipped project (I am saying `projects` because they are not `dlls` at the moment of patching) -- this can annoy some customers. But I agree that short summary would help.
