### ISSUE TITLE
No longer able to publish to the PSGallery due to outdated default PowerShellGet Module in build VMs?

### ISSUE THREAD

**Issue by pldmgg** [appveyor/ci#2639]
All of my AppVeyor builds are failing to deploy to the PSGallery with an error that comes from PowerShellGet's `Publish-Module` cmdlet:

```
Command executed with exception: Failed to publish module 'winssh': 'Response status code does not indicate success: 400 (A client version '4.1.0' or higher is required to be able to publish packages. Install the latest version of NuGet client or install the latest version of PowerShellGet module using the instructions provided at https://aka.ms/installing-powershellget. Please contact cgadmin@microsoft.com to get more details.).
```

Example:
https://ci.appveyor.com/project/pldmgg/winssh/branch/master

Since everything was working fine yesterday, I think this is because of something that was announced earlier this week and finally took effect yesterday/today...

https://blogs.msdn.microsoft.com/powershell/2018/09/12/new-look-and-features-for-powershell-gallery/

...specifically...

> Most important: Publishers must update to PowerShellGet module version 1.6.8 or higher to publish to the PowerShell Gallery. Older versions of PowerShellGet are fine for find, save, install, and update functions, but not for publishing. 

Can AppVeyor update the default PackageManagement/PowerShellGet Module version in build VMs?

**Comment by FeodorFitsner** [comment]
OK, you can't publish because your build uses `WMF 5` image which is quite outdated and will be discontinued soon.

On regular `Visual Studio 2015` and `Visual Studio 2017` there is WMF 5.1 installed and publishing of test module to PowerShell Gallery works: https://ci.appveyor.com/project/appveyor-tests/psgallery-test/build/1.0.9

In contrast, publishing from `WMF 5` image doesn't work: https://ci.appveyor.com/project/appveyor-tests/psgallery-test/build/1.0.12

...but we are updating `PowerShellGet` module anyway.

**Comment by pldmgg** [comment]
Oh wow, I didn't even notice that! I updated the build image and everything works fine now.

In any case, thanks for updating PowerShellGet!
