### ISSUE TITLE
LLVM Compiler Toolchain Visual Studio Extension

### ISSUE THREAD

**Issue by sylveon** [appveyor/ci#2665]
Clang 7 has been installed in the workers, and the installer for it does not installs the LLVM-vs2014 toolset for VS anymore. The now recommended way of building with Clang on Visual Studio is [this extension](https://marketplace.visualstudio.com/items?itemName=LLVMExtensions.llvm-toolchain), which adds a `llvm` toolset. Currently, projects using the llvm toolset will just fail without this addon installed. Installing the addon in the workers will allow to use CI for those projects.

**Comment by CFSworks** [comment]
Just ran up against this brick wall too. Note however that the extension is for VS2017, so it cannot be installed in the VS2013 or VS2015 images.

**Comment by FeodorFitsner** [comment]
Will deploy the extension early next week.

**Comment by CFSworks** [comment]
That's good for VS2017 - however, my project is explicitly VS2015. Do I have to give up on Clang entirely now that the toolchain has been removed from that image?

**Comment by FeodorFitsner** [comment]
I'm not sure if 6th and 7th LLVMs can be installed side-by-side as each new installation is asking about removing previous one. Will look into that.

Moving to VS 2017 is an option too.

**Comment by sylveon** [comment]
Alternatively, it's possible to copy the LLVM-vs2014 and LLVM-vs2014xp target files from Clang 6 to preserve them while still keeping Clang 7 installed.

**Comment by CFSworks** [comment]
@sylveon That's a good idea actually; I'm wondering about doing that myself.

The LLVM <=6 toolset files work by adding `msbuild-bin` to the binary search path, where Clang is copied as `cl.exe` - so it'd be necessary to copy the LLVM 7 binaries into such a directory. LLVM 7's toolset file, on the other hand, actually changes the path to cl/lld to LLVM's version.

The only problem is that this is a nonstandard workaround, so if the AppVeyor images were to include this, they wouldn't be shipping "vanilla" LLVM anymore (i.e. the build process working on AppVeyor no longer indicates that it would work on "vanilla" LLVM because it'd be necessary to replicate AppVeyor's workaround).

Really I'm just kind of surprised at this change in the first place. As recently as [this March](https://web.archive.org/web/20180320162427/https://llvm.org/builds/) LLVM was supporting versions as old as MSVC 2010 - I wouldn't have been surprised if they dropped that and 2012, since I don't know if anybody uses those anymore. But MSVC 2015 is still very widely-used (case in point, AppVeyor still bothers to maintain images for it) and I can't find any mention of this anywhere. I'm thinking an issue on the LLVM bug tracker might be in order.

**Comment by CFSworks** [comment]
An update: It seems like [at least one LLVM reviewer](https://reviews.llvm.org/D42762?id=132243#inline-374042) confirms that the VSIX does work for VS2015.

@FeodorFitsner I'll be seeing what I can do about installing the VSIX in my local VS2015 environment - if it's workable, could you do this for the AppVeyor VS2015 images as well?

I still don't have any good ideas for VS2013, though.

**Comment by FeodorFitsner** [comment]
Sure, let me know about your findings.

**Comment by CFSworks** [comment]
I only use the VS2015 *build tools* in my local environment. But for what it's worth, I was able to extract the .vsix manually and my build pipelines work without any manual intervention (besides using `llvm` instead of `LLVM-vs2014` of course)

I have an [answer on StackOverflow here](https://stackoverflow.com/questions/52407398/llvm-7-0-does-not-provide-specific-platform-toolset-on-visual-studio-2015/52582414) detailing where I extracted the vsix.

Assuming the AppVeyor images use the full VS2015, it should be a matter of installing the vsix just as you would on VS2017. I still have no ideas about VS2013 - that one might require the manual method.

**Comment by zufuliu** [comment]
The vsix at https://marketplace.visualstudio.com/items?itemName=LLVMExtensions.llvm-toolchain or source at http://llvm.org/svn/llvm-project/llvm/trunk/tools/msbuild doesn't works for LLVM 7.0 on AppVeyor in Visual Studio 2017 Image:

1. SupportJustMyCode (`/JMC`) doesn't support by clang-cl in LLVM 7.0, should ignore this option.
2. `/DEBUG:FASTLINK` doesn't support by lld-link, which is enabled by default (`$(UseLldLink)`), should internal replaced to `/DEBUG:FULL` like lld-link in 8.0 SVN.

See https://github.com/zufuliu/llvm-utils for working one for VS2017, and https://ci.appveyor.com/project/zufuliu/notepad2 for working example.

**Comment by zufuliu** [comment]
The visx also doesn't support XP target and ARM64 (LLVM 8.0).

**Comment by sylveon** [comment]
I've fixed the /JMC option in a merge request to the extension: https://reviews.llvm.org/D56034. As you mentioned fast link is fixed in the next release of LLVM (they should make it use GHASH imo). I believe ARM64 wouldn't be hard to make work either but I have nothing to test if the resulting binary runs.

**Comment by zufuliu** [comment]
Dear All, Happy New Year.

I added LLVM MSBuild scripts (support ARM64 and XP targeting) for Visual Studio 2010, 2012, 2013, 2015, 2017 and 2019 at https://github.com/zufuliu/llvm-utils, hope they can help you.

See install step for AppVeyor build image at https://github.com/zufuliu/llvm-utils#install-to-appveyor-build-image


@sylveon I think files in https://github.com/zufuliu/llvm-utils/tree/master/VS2017 folder can help you to simplify code in http://llvm.org/svn/llvm-project/llvm/trunk/tools/msbuild folder, and to add ARM64 and Windows XP target.
