### ISSUE TITLE
MSYS2 update (October 2018)

### ISSUE THREAD

**Issue by MSP-Greg** [appveyor/ci#2703]
MSYS2 build tools have been updated, updating one chain (64 or 32) is approx. half a GB of 'unzipped' files.

Also, MSYS2 has updated OpenSSL from 1.0.2 to 1.1.1.  Most of their packages that build with OpenSSL have also been updated.

Apologies for always mentioning it, but there are times when partial updates to 'base', base-devel', or 'toolchain' cannot be done without a full update.  Since there are quite a few installed packages, this can take some time.  I did inquire, and the response was that there will be times when partial updates will fail...

Thanks, Greg

**Comment by maynardGK** [comment]
I am having an issue building graphicsmagick in appveyor using MSYS2.
My final attempt results in a robust script https://github.com/maynardGK/gdl/pull/4/commits/9d3efa776572fc682317858185a97967f7b219e9
that I have home-tested on my -frozen- msys2 (gcc 5.3 vintage) but the build on appveyor generates an error I cannot get past. https://ci.appveyor.com/project/maynardGK/gdl/builds/20072941

One issue I had, which may be related to an update, is that I needed to download libtool
to my local directory in order to proceed.  AFAIK,  ltdl and cousins are only needed during the configure/make.
