### ISSUE TITLE
Invalid MSBuild version on image VS 2019 Preview

### ISSUE THREAD

**Issue by VladislavAntonyuk** [appveyor/ci#2776]
AR: Version 15.9
ER: Version 16

MSBuild
The MSBuild toolset version has been changed from 15.0 to Current. MSBuild.exe is now in %VSINSTALLDIR%\MSBuild\Current\Bin\MSBuild.exe.
MSBuild (and Visual Studio) now targets .NET Framework 4.7.2. If you wish to use new MSBuild API features, your assembly must also upgrade, but existing code will continue to work.

**Comment by IlyaFinkelshteyn** [comment]
It will be fixed in next image update. For now simple workaround is to add update `path`  environment variable with this command:

```
set path=C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin;%path%
``` 

in `cmd` mode at `install` stage.

[Here](https://www.appveyor.com/docs/build-configuration/#script-blocks-in-build-configuration) you can read how to run scripts during the build.

**Comment by IlyaFinkelshteyn** [comment]
New Windows images [deployed](https://www.appveyor.com/updates/2019/02/11/)
