### ISSUE TITLE
Python3.7 not available on Ubuntu image

### ISSUE THREAD

**Issue by swaldhoer** [appveyor/ci#2779]
The [docs](https://www.appveyor.com/docs/linux-images-software/#python) say python3.7 should be available on the Ubuntu image, but as far as I see it, it is missing:

```
whereis python
python: /usr/bin/python3.5m
/usr/bin/python2.7
/usr/bin/python3.5
/usr/bin/python
/usr/bin/python2.7-config
/usr/lib/python2.7
/usr/lib/python3.5
/etc/python2.7
/etc/python3.5
/etc/python
/usr/local/lib/python2.7
/usr/local/lib/python3.5
/usr/include/python2.7
/usr/share/python
/opt/az/bin/python3.6
/opt/az/bin/python3.6m
/opt/az/bin/python3.6-config
/opt/az/bin/python3.6m-config
/usr/share/man/man1/python.1.gz
```

[full log](https://ci.appveyor.com/project/swaldhoer/native-lua/builds/21049342/job/6rsw4p8tnbtck5ye#L19)

Am I missing something or is it bug?

**Comment by Wasapl** [comment]
Python versions installed in virtualenvs which resides in /home/appveyor directory.
The easiest way to use those versions is to use `stack: python 3.7.1` command in appveyor.yml

**Comment by swaldhoer** [comment]
Thanks for pointing me to this!
But this `stack:` seems to have one problem: Only `user` python is set to the specified one, the `sudo` python is still the one it is from the start:
- For building I use `python waf build` and it works. I can be sure it uses the correct python version, as I use f-strings which are available starting from python3.6, and my log is correctly printed (see [here](https://ci.appveyor.com/project/swaldhoer/native-lua/build/job/njgc243ru5hnx3mm#L30))
- Now in the install step I ran `python waf install` and python tells, it does not know what to do with f-strings (see [here](https://ci.appveyor.com/project/swaldhoer/native-lua/build/job/njgc243ru5hnx3mm#L166)). Therefore it still seems to use the default python.

Am I using `stack` wrong? Is it broken? Or not designed to be used like that?

**Comment by Wasapl** [comment]
This is due to the architecture of Virtualenv.
Then you set `stack: python 3.7.0` under the hood of Appveyor `source venv3.7.0/bin/activate` executed. It sets all interpreter and library paths to those in `venv3.7.0` folder. But it all happens inside of current bash session. Then you do `sudo python` sudo creates another session with root privileges and it does not know about changes made by virtualenv.
I'm not aware of that `python waf install` do, but Is it necessary to run it with sudo?
If it is you may do this trick:
`sudo bash -c 'source venv3.7.0/bin/activate && python waf install'`
This will instruct sudo to run bash with root privileges, bash will activate virtualenv with python 3.7.0 and execute `python waf install`.

**Comment by swaldhoer** [comment]
After the build finished successfully, I want to install, in order to test. Therefore I would install into the typical directories which is `/usr/local/bin`, `/usr/local/` etc.
So yes, I need to run this with root privileges.

The virtualenv can not be activated as you suggested by `venv3.7.0/bin/activate` (see [here](https://ci.appveyor.com/project/swaldhoer/native-lua/builds/21084785/job/79n7m231vct1ragx#L156)).

**Comment by Wasapl** [comment]
Oh, sorry I mislead you. Absolute path should be used there:
```
sudo bash -c 'source /home/appveyor/venv3.7.0/bin/activate && python waf install'
```

**Comment by swaldhoer** [comment]
Thanks, solved the problem.
