### ISSUE TITLE
Bundler 2.0 for Ruby >= 2.3, Bundler 1.17.3 for all Rubies

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#2829]
Bundler 2.0 update: https://bundler.io/blog/2018/11/04/an-update-on-bundler-2.html

**Comment by larskanis** [comment]
You should pre-install both bundler-1.17.x and bundler-2.x on Ruby >= 2.3. This can be done like so:
```
gem install --no-document bundler "bundler:~>1.17"
```

This is because many projects still have a `Gemfile.lock` which is tagged to bundler-1.x, which bundler-2.x can not handle. However in this case bundler-1.x is automatically invoked. So installing both solves this issue. This works even on Ruby-2.6, which includes bundler-2.x by default.

**Comment by FeodorFitsner** [comment]
Nice catch, thank you!

**Comment by IlyaFinkelshteyn** [comment]
New Windows images [deployed](https://www.appveyor.com/updates/2019/02/11/)
