### ISSUE TITLE
Visual Studio 2019 version 16.0.0 Preview 2.1

### ISSUE THREAD

**Issue by EwoutH** [appveyor/ci#2834]
Would be nice if the `Visual Studio 2019 Preview` image could be updated to VS2019 [Preview 2](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#VS2019_Preview2) with the [windows-images-update-2019-02-03](https://github.com/appveyor/ci/milestone/142) milestone.

**Comment by VladislavAntonyuk** [comment]
Version 2.1 is released

**Comment by EwoutH** [comment]
And [Preview 2.2](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#--visual-studio-2019-preview-22-) also

**Comment by IlyaFinkelshteyn** [comment]
New Windows images [deployed](https://www.appveyor.com/updates/2019/02/11/)

**Comment by jskeet** [comment]
Is it expected that there's any delay between them being deployed and being available? I'm still getting errors about the right version of the .NET Core SDK not being present:

```text
A compatible installed dotnet SDK for global.json version: [3.0.100-preview-010184] from [C:\projects\nodatime\global.json] was not found
Please install the [3.0.100-preview-010184] SDK or update [C:\projects\nodatime\global.json] with an installed dotnet SDK:
  1.0.0-preview2-003156 [C:\Program Files\dotnet\sdk]
  1.0.1 [C:\Program Files\dotnet\sdk]
  1.0.2 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.105 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009812 [C:\Program Files\dotnet\sdk]
```

**Comment by IlyaFinkelshteyn** [comment]
@jskeet can you please send a link to the build?

**Comment by jskeet** [comment]
https://ci.appveyor.com/project/nodatime/nodatime/builds/22299705

That was triggered via hitting "New Build". If that doesn't use new images, that would explain things, but I'd (perhaps naively) expect it to pick up the latest one.

**Comment by IlyaFinkelshteyn** [comment]
@jskeet Thank you, I found it. Visual Studio is actually updated on `Visual Studio 2019 Preview` image (which you can check if you [RDP](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/) to build VM and press Help > About in VS). However this does not automatically installed last runtime and SDK.

Please check [my fork build history](https://ci.appveyor.com/project/IlyaFinkelshteyn/nodatime/history) with workaround. Changes are self-explainable. I did not send a PR as you probably prefer to wrap that workaround into script in you own way.

Filed https://github.com/appveyor/ci/issues/2862 to add this to the `Visual Studio 2019 Preview`.

However I am not sure you really need this image. If you install SDK and runtime on the fly using standard `Visual Studio 2017` image you will enjoy faster build start because main images are on "pre-heated" VMs.

**Comment by jskeet** [comment]
Great, thanks very much. Will make that change now.

**Comment by jskeet** [comment]
Looks like it's working: https://github.com/nodatime/nodatime/pull/1281
Note that I haven't installed the runtime separately - just the SDK, as that includes the runtime as far as I'm aware.

At least, the build works :)
