### ISSUE TITLE
Qt 5.12.3, 5.12.4, 5.13.0

### ISSUE THREAD

**Issue by tsteven4** [appveyor/ci#2923]
Please add Qt 5.12.3 to the next-images-update milestone.

**Comment by patrickelectric** [comment]
Update the title to 5.12.4 ;), Since a newer version is available
https://blog.qt.io/blog/2019/06/17/qt-5-12-4-released-support-openssl-1-1-1/

**Comment by nschimme** [comment]
Please note that Qt 5.12.4 requires OpenSSL 1.1.1 as opposed to OpenSSL 1.0.2 in previous 5.12.x versions. This will most likely cause user builds to fail... but with OpenSSL 1.0.2 being slated for EOL by end of this year maybe it's a good thing to break the builds.

**Comment by heydojo** [comment]
> Please note that Qt 5.12.4 requires OpenSSL 1.1.1 as opposed to OpenSSL 1.0.2 in previous 5.12.x versions. This will most likely cause user builds to fail... but with OpenSSL 1.0.2 being slated for EOL by end of this year maybe it's a good thing to break the builds.

This change in Qt is generally a sensible one IMO but not for a LTS point release. There was no need to remove backwards compatibility with Openssl 1.0.2 (if what you say is true.) The differences between 5.12.3 and 5.12.4 are causing lots of problems. Such as that vcpkg is now stuck on 5.12.3 because there are breaking changes in Qt 5.12.4 that they are struggling to work around.

Maybe it would be possible to ensure that both Qt 5.12.3 and Qt 5.12.4 are available? Some developers may not be ready to move away from Qt 5.12.3 just yet.

**Comment by tsteven4** [comment]
How about mapping the latest 5.12, now 5.12.4, to 5.12 instead. That way 
users that need to force an old version because they aren't ready for 
the OpenSSL change can do so, and the rest of us can automatically used 
the latest 5.12, currently 5.12.4.

> |C:\Qt\5.12| mapped to |C:\Qt\5.12.3| for backward compatibility)

**Comment by IlyaFinkelshteyn** [comment]
We did not risk that because we heard about big number of issues with 5.12.4. You can check [this script](https://github.com/appveyor/build-images/blob/master/scripts/Windows/prepare_qt.ps1) and see how to modify it (or part of it) and run at `init` or `install` stage to do changes you need.

**Comment by tsteven4** [comment]
How about a link 5.12.latest?  I don't want to have to make a change every
time there is a new patch version  (5.12.x)

Btw, we haven't found any issues with 5.12.4.

**Comment by IlyaFinkelshteyn** [comment]
What happens with 12.3/12.4 is an exception, rather than a rule. Usually we keep only x.x.latest and make a mapping for x.x to x.x.latest. In this case we did not take a risk to break many people and kept 12.3 as default in parallel. For next update after 12.4  we will probably come back to the regular approach.

**Comment by nschimme** [comment]
I have not found any issues with Qt 5.12.4 either. My project uses OpenSSL but I was able to have it switch to 1.1.1 without any issues by just packaging the correct DLLs:
https://github.com/MUME/MMapper/pull/150/files

**Comment by nschimme** [comment]
Posting this here to get more visibility. I had a 32bit Shining Light Productions OpenSSL 1.1.1 issue when building on Windows 10 because Microsoft provides a default LibreSSL library under `C:/Windows/System32/libcrypto.dll`.

If your MinGW and CMake compiled app is having trouble you might have noticed that it is trying to link with `C:/Windows/System32/libcrypto.dll` or `C:/OpenSSL-v111-Win32/lib/MinGW/libcrypto.a`. When you launch the resulting program, it then proceeds to complain about a missing `libcrypto.dll` rather than the expected `libcrypto-1_1.dll`.

To resolve this, simply tell CMake to find libraries with the `.lib` extensions instead for linking:
```
    if(MINGW AND "${CMAKE_SIZEOF_VOID_P}" EQUAL "4")
        set(CMAKE_FIND_LIBRARY_SUFFIXES .lib)
    endif()
    find_package(OpenSSL)
```
