### ISSUE TITLE
Update MSYS2

### ISSUE THREAD

**Issue by MSP-Greg** [appveyor/ci#2927]
Currently, updating only the 64 bit toolchain results in 82 MiB downloaded, 462 MiB installed...

**Comment by IlyaFinkelshteyn** [comment]
[internal note] use https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_msys64.ps1, it is idempotent

**Comment by vadz** [comment]
Not sure if it's really useful to report this, but this update resulted in compiler (which is now gcc 9.1) crashing reliably when compiling our unit tests, see e.g. [this build log](https://ci.appveyor.com/project/wxWidgets/wxwidgets/builds/26445788/job/ovajab6v4ltp5h70).

**Comment by IlyaFinkelshteyn** [comment]
Do you believe it is MSYS issue. or it is something AppVeyor can fix? As a temporary workaround you can set image to the previous one, `image: Previous Visual Studio 2015` I believe in your case. But this workaround would be valid **only till next update**.

**Comment by MSP-Greg** [comment]
@vadz

Just for testing, have you tried a 64 bit build using MSYS2?  Most the building I'm familiar with is Ruby itself or extension gems.  In many cases, the toolchain is updated, so we've always been using the most current MSYS2 gcc compilers.  Never had any issues.  I've also built a fair number of MSYS2 packages, but I don't recall how often I ran 32 bit builds...

**Comment by vadz** [comment]
Thanks for your replies! I had indeed  switched to the previous image to avoid this problem for now, but since then another member of our project (@MaartenBent) has found [a workaround](https://github.com/wxWidgets/wxWidgets/pull/1464) for this bug, so the problem is fixed now.

I've mostly commented here just in case it could be useful for others running into the same problem, as it took some time to realize that the new build failures were due to the compiler update (and not just due to some cosmic rays triggering compiler crashes).
