### ISSUE TITLE
Docker build for new 1903 images

### ISSUE THREAD

**Issue by olegburov** [appveyor/ci#3023]
Same as https://github.com/appveyor/ci/issues/2676

Add support for Windows Service Core version 1903 and Windows Nano Server 1903:

- `mcr.microsoft.com/windows/servercore:1903`
- `mcr.microsoft.com/windows/nanoserver:1903`

**Comment by IlyaFinkelshteyn** [comment]
@olegburov thank you for bringing this up. Do I understand correctly that if we add those new 1903 images alongside with [others](https://ci.appveyor.com/project/appveyor-tests/win2k19-azure/builds/24580220#L89) to our `Windows Server 2019` VM image, it will solve the problem?

**Comment by olegburov** [comment]
@IlyaFinkelshteyn it depends on Windows Server version that your VM image is based on. 

With Windows Containers the host OS must match the Windows Container image. For example, to run a container based on the `mcr.microsoft.com/windows/servercore:1903` or `mcr.microsoft.com/windows/nanoserver:1903`, the host OS msut be Windows Server 2019 v1903 (SAC).

See here for details: https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility

**Comment by cYCL157** [comment]
i came across this looking to do the same.  With the current 2019 server image I am able to build 1809 with process isolation and 1803 with hyperv isolation -- but also looking to do 1903 as well.

**Comment by IlyaFinkelshteyn** [comment]
Initially I was under impression that it will work in `hyperv` isolation mode on our `Window Server 2019` image (which is based on Long-Term Servicing Channel release of Windows Server 2019). Apparently it is not supported.

We have a [private build cloud](https://www.appveyor.com/docs/build-environment/#private-build-cloud) solution. Now we are re-branding it to BYOD (Bring Your Own Cloud) and adding a lot of automation to make it easy to set up

We prepared a template for you to build your own Azure image based on `Windows Server version 1903 with Containers`. 

If you are interested, please let us know and we will enable this feature for your AppVeyor accounts.

To setup, please follow [those instructions](https://www.appveyor.com/docs/server/#azure-vms) but instead of calling `.\connect-to-azure.ps1`, call `.\connect-to-azure.ps1 -appveyor_url https://ci.appveyor.com -image_description "Windows Server 2019 version 1903" -packer_template .\minimal-windows-server-1903.json`. 

As a result new (private) image called `Windows Server 2019 version 1903` will be available to your AppVeyor projects and you can [add it](https://www.appveyor.com/docs/build-environment/#choosing-image-for-your-builds) to your build matrix.

**Comment by FeodorFitsner** [comment]
@olegburov Both `mcr.microsoft.com/windows/servercore:1903` and `mcr.microsoft.com/windows/nanoserver:1903` has been installed on `Visual Studio 2019` image which now has Docker/LCOW/WSL. `Windows Server 2019` is not going to be updated going forward. Please switch to `Visual Studio 2019`.
