### ISSUE TITLE
Android SDKs and Mobile development with C++ on Visual Studio 2019 image

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [appveyor/ci#3112]

**Comment by VladislavAntonyuk** [comment]
Android sdk platform 29

**Comment by VladislavAntonyuk** [comment]
The issue is not fixed on Visual Studio 2019. I get this error: error XA5207: Could not find android.jar for API Level 29. This means the Android SDK platform for API Level 29 is not installed. Either install it in the Android SDK Manager (Tools > Open Android SDK Manager...), or change your Xamarin.Android project to target an API version that is installed.

**Comment by FeodorFitsner** [comment]
Do you have a public repro project to test?

**Comment by FeodorFitsner** [comment]
@VladislavAntonyuk we've just deployed an updated image with SDKs Level 19 through 29. Let me know how that worked for your project.

**Comment by VladislavAntonyuk** [comment]
@FeodorFitsner the build succedeed. As a task imprivement if it is possible please switch to Google repository in SDK manager.

**Comment by FeodorFitsner** [comment]
Thanks for the update. How would you switch repository (UI or command line)?

**Comment by VladislavAntonyuk** [comment]
@FeodorFitsner I connected to the VM, and after starting the SDK manager, I saw the Microsoft repository, which bothers me a bit, because you use the Google repository. I would say it is a task improvement and is not required if you have higher priority tasks
