### ISSUE TITLE
Conditions for entire deployment process

### ISSUE THREAD

**Issue by srogovtsev** [appveyor/ci#317]
It'd be helpful to have a condition (e.g. "deploy only from `master`") that will span entire deployment tab (now it affects only deployment provider it's configured for). Use case is simple: I have a complicated deployment process that includes pre-/post-build scripts and a provider, and I want to run all that only for build on stable branch. For now I have to wrap both scripts in `If($Env:APPVEYOR_REPO_BRANCH -eq 'master')`.

Same thread on AppVeyor support center: http://help.appveyor.com/discussions/suggestions/716-conditional-deployment

**Comment by cwharris** [comment]
I second this. I'm also trying to determine the right way to make deployments work with GitHub. I'm not so great with bash/ps, but right now I'm thinking I'll need something along the lines of `${APPVEYOR_PULL_REQUEST_NUMBER} == undefined && ${APPVEYOR_REPO_BRANCH} == "master"` as my conditions for deployment.

**Comment by IlyaFinkelshteyn** [comment]
Hi Christopher,

I think originally this issue was created by @srogovtsev about creation condition for **whole** deployment, not for specific provider.

I have feeling that your question is about how to implement specific condition. In your case it can be done like this:

```
deploy:
- provider: <you_provider>
<you_provider_settings>
  on:
    branch: master
    APPVEYOR_PULL_REQUEST_NUMBER: ''
```
This will work exactly as you want, with difference that `branch` condition will be evaluated first and if it false, `APPVEYOR_PULL_REQUEST_NUMBER` will not be evaluated. For `APPVEYOR_PULL_REQUEST_NUMBER` condition is just `''` instead of JavaScript-style `undefined`.

--ilya.

**Comment by FeodorFitsner** [comment]
I'm closing this issue because it has been inactive for a long time.
