### ISSUE TITLE
Qt 5.12.6

### ISSUE THREAD

**Issue by tsteven4** [appveyor/ci#3197]
Please add Qt 5.12.6 to the next-images-update milestone, and move the Qt 5.12 links to point to it.

Also correct https://www.appveyor.com/docs/windows-images-software/#qt, which doesn't mention the C:\Qt\5.12 link, and doesn't mention Qt 5.12 on Visual Studio 2017.

Qt offline installers are at https://download.qt.io/archive/qt/5.12/5.12.6/ but the release hasn't quite been announced yet.

**Comment by tsteven4** [comment]
Qt 5.12.6 has been released:
https://www.qt.io/blog/qt-5.12.6-released

**Comment by FeodorFitsner** [comment]
Great, thanks for letting know! Usually, it makes sense to wait a little before rolling it our until any blocking issues re-surface :)

**Comment by tsteven4** [comment]
Can we please move forward with this?

**Comment by FeodorFitsner** [comment]
It's going to be installed on VS 2019 image this week: https://github.com/appveyor/ci/issues/3248

**Comment by dalboris** [comment]
Thx for the update, Qt 5.12.6 is definitely appreciated! :)

However, as the OP said, the page https://www.appveyor.com/docs/windows-images-software/#qt currently does NOT mention:

"C:\Qt\5.12 mapped to C:\Qt\5.12.6 for backward compatibility"

Since such mention is made for all other Qt versions, this led me to believe that there were no such symlink, so I was until today using the explicit 5.12.4, 5.12.5, etc., breaking my build each time AppVeyor upgraded to a newer version.

As it turns out, there is in fact such symlink, so I'm now pointing to C:\Qt\5.12 and the future upgrade to 5.12.7 shouldn't break my build.

Could the page https://www.appveyor.com/docs/windows-images-software/#qt  be updated to mention the symlink?

Thank you!
