### ISSUE TITLE
Add Node.js development workload to VS 2019 image

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3199]

**Comment by rsilvaworth** [comment]
Hello @FeodorFitsner, do you have any update about this? We're using the Visual Studio 2019 Preview version, that is the only one that supports dotnet 3.1, but we cannot find node 8 there (we need it because of an external dependency).

![image](https://user-images.githubusercontent.com/53431559/69243975-6c6f5880-0ba4-11ea-97f4-3bb6bc7baac5.png)

**Comment by rsilvaworth** [comment]
We also tried Visual Studio 2019, but the node doesn't seem to be there either.

**Comment by FeodorFitsner** [comment]
Try `8.16.0` version and let me know if that worked.

**Comment by rsilvaworth** [comment]
@FeodorFitsner, yes, it worked. Thank you!
