### ISSUE TITLE
secure-file support for macOS

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#3214]

**Comment by jacobq** [comment]
Any progress on this? Looks like it was supposed to be part of the "next" macos image update, but the image was just updated and the problem persists.

```
./appveyor-tools/secure-file -decrypt bitbucket_ssh_key.enc -secret $decryption_key -out ~/.ssh/id_rsa
/usr/local/Cellar/appveyor-build-agent/7.0.2653/bash-shell.sh: line 62: ./appveyor-tools/secure-file: Permission denied
Command exited with code 126
```

**Comment by FeodorFitsner** [comment]
Working on that. Thanks for your patience!

**Comment by jacobq** [comment]
Looks like this is still missing in the 6/7/2020 update and continues to block our ability to use AppVeyor for MacOS builds. Would you be willing to suggest some work-arounds for this? Perhaps I should use [`age`](https://github.com/FiloSottile/age) and set the key as an environment variable from the `https://ci.appveyor.com/project/me/my-project/settings/environment` interface?

**Comment by AdmiringWorm** [comment]
@jacobq looks like that the correct permission stat has been forgotten to be set.

You could try this before running the file itself:
```
sudo chmod +x appveyor-tools/secure-file
```
or
```
sudo chmod 755 appveyor-tools/secure-file
```

Both of the above should work (from Linux experience, but OSX uses the same permissions I believe).

**NOTE: I have not tested this myself**

**Comment by jacobq** [comment]
> @jacobq looks like that the correct permission stat has been forgotten to be set.

Thanks for the suggestion, @AdmiringWorm, I didn't realize that it might be that simple. Adding the executable flag to that file fixed the problem! (Now I am hitting another block, which has to do with my script assuming that `sh: ...` only applies to Linux, but that's my problem.) @FeodorFitsner, I opened a PR to fix this upstream: https://github.com/appveyor/secure-file/pull/10 Would you mind taking a look?

```
iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))


    Directory: /var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          07/15/2020    13:30                8e2e1615-13f5-40d8-89d6-1ca91bd40196

ls -alhR appveyor-tools/
total 88
drwxr-xr-x   9 appveyor  staff   288B Jul 15 13:30 .
drwxr-xr-x  40 appveyor  staff   1.3K Jul 15 13:30 ..
-rw-r--r--   1 appveyor  staff   104B Apr 29 17:56 secure-file
-rw-r--r--   1 appveyor  staff   431B Apr 29 17:56 secure-file.deps.json
-rw-r--r--   1 appveyor  staff    12K Apr 29 17:56 secure-file.dll
-rw-r--r--   1 appveyor  staff    12K Apr 29 17:56 secure-file.exe
-rw-r--r--   1 appveyor  staff   176B Apr 29 17:56 secure-file.exe.config
-rw-r--r--   1 appveyor  staff   3.3K Apr 29 17:56 secure-file.pdb
-rw-r--r--   1 appveyor  staff   154B Apr 29 17:56 secure-file.runtimeconfig.json
```

I suppose another work-around would be to invoke `dotnet appveyor-tools/secure-file.dll ...` since it appears the `secure-file` program is just a wrapper script for that.

**Comment by FeodorFitsner** [comment]
Thank you for opening PR with the fix. I fixed it slightly differently though: https://github.com/appveyor/secure-file/blob/master/install.ps1#L10, so it won't fail on Windows PowerShell where `$isWindows` is not defined. Let me know how it worked.

**Comment by jacobq** [comment]
> ...so it won't fail on Windows PowerShell where `$isWindows` is not defined. Let me know how it worked.

Where can I open an issue to correct the documentation regarding this? I looked all over for something like `CI_MAC`, `$isMacOS`, etc. but did not see it. Furthermore, the ["Getting started with AppVeyor for Linux"](https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/) suggests that using `$isWindows` is perfectly safe.

I'll test the updated script shortly, but if those variable names are correct then it should do exactly what I want.

**Comment by AdmiringWorm** [comment]
> I'll test the updated script shortly, but if those variable names are correct then it should do exactly what I want.

Those variable names should be correct, as they are set by PowerShell Core itself, but not by Windows PowerShell.

Alternatively `$IsCoreCLR -and (-Not $isWindows)` could be an alternative if somehow those do not work.

**Comment by jacobq** [comment]
> Alternatively `$IsCoreCLR -and (-Not $isWindows)` could be an alternative if somehow those do not work.

My PR used `(-Not ($isWindows))` but was rejected.
https://github.com/appveyor/secure-file/pull/10/files#diff-00ded903b18eba5a23a1d8ec86c58e94R10

**Comment by jacobq** [comment]
> Those variable names should be correct, as they are set by PowerShell Core itself, but not by Windows PowerShell.

@AdmiringWorm can you share a link that documents this? In particular, the variable of interest is `$isMacOS` as used in the commit intended to fix this (I could not find it in the AppVeyor documentation):
https://github.com/appveyor/secure-file/commit/fc44f5c5f2fb184fe738814f373c16cb69c30929

**Comment by AdmiringWorm** [comment]
> My PR used (-Not ($isWindows)) but was rejected.

yes, but that is because that variable isn't set by Windows PowerShell, neither are `$IsCoreCLR`.
I would still suggest to keep `$isLinux -or $isMacOS`.

> can you share a link that documents this?

I have not seen it on appveyor, but I have been doing quite a bit of PowerShell Core so remembered it was available when running underneath it.
The PS Core docs of these variables are here: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7#iscoreclr

**Comment by FeodorFitsner** [comment]
AppVeyor build agent additionally sets `$isWindows` for Windows PowerShell, but it's more preferably the script should normally work outside CI environment.

**Comment by jacobq** [comment]
> yes, but that is because that variable isn't set by Windows PowerShell, neither are `$IsCoreCLR`.

Ah, I didn't realize that Windows PowerShell was different than PowerShell Core. That makes sense now. Basically, the script needs to work under the assumption that it is running in Windows when none of these variables are available (including `$isWindows`). The logic in my version would've resulted in the `chmod` running even in Windows' case.

> I would still suggest to keep `$isLinux -or $isMacOS` if it works.

100% agree. I simply didn't know that (1) `$isMacOS` was available and (2) that `$isWindows` was not.

> > can you share a link that documents this?
> ...
> The PS Core docs of these variables are here: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7#iscoreclr

Thanks for the link. As someone who rarely uses (= does not have a deep understand of) PowerShell, I seem to hit a lot of "gotchas". For example, I didn't realize that variable names were case insensitive. It seems weird that AppVeyor documents an `$isLinux` variable different than the convention used by PowerShell core: `$IsLinux`. 

> AppVeyor build agent additionally sets `$isWindows` for Windows PowerShell, but it's more preferably the script should normally work outside CI environment.

Got it. Feel free to close this issue as it appears to be fixed by https://github.com/appveyor/secure-file/commit/fc44f5c5f2fb184fe738814f373c16cb69c30929
