### ISSUE TITLE
MSYS 2

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#352]
Discussion: http://help.appveyor.com/discussions/suggestions/615-support-for-msys2

Installation path: `C:\msys64`

Installation:

MSYS2: http://sourceforge.net/projects/msys2/files/Base/x86_64/msys2-x86_64-20150512.exe/download

Run `C:\msys64\msys2_shell.bat`:
```
pacman -Sy
pacman -S pacman
update-core
pacman --sync base-devel mingw-w64-{x86_64,i686}-toolchain
pacman --sync mingw-w64-{x86_64,i686}-cmake
pacman --sync mingw-w64-{x86_64,i686}-ninja
pacman --sync mingw-w64-{x86_64,i686}-gtkmm
pacman --sync mingw-w64-{x86_64,i686}-wxWidgets
pacman --sync gyp-svn
pacman --sync cmake
```

Additional notes: http://sourceforge.net/p/msys2/wiki/MSYS2%20installation/

**Comment by FeodorFitsner** [comment]
Install: http://sourceforge.net/projects/msys2/files/Base/x86_64/msys2-x86_64-20150512.exe/download

```
pacman -Sy
pacman -Su
update-core
pacman --sync mingw-w64-x86_64-gcc
pacman --sync mingw-w64-i686-gcc
pacman --sync base-devel
```

**Comment by mingwandroid** [comment]
Thanks @FeodorFitsner 

I think the best strategy is:

```
[1] Update the core from cmd.exe
cmd.exe C:\msys64\usr\bin\bash.exe --login -c "update-core"
```

```
[2] launch msys2_shell.bat and do the rest (in one line):
pacman --sync base-devel mingw-w64-{x86_64,i686}-toolchain
```

Explanation:

`[1]` update-core does pacman -Sy first anyway, followed by updating msys2's core. Running it via bash.exe --login -c means it will automatically exit the shell afterwards which avoids problems with msys2 DLL address overlap, where the newly updated DLL has a different base address and conflicts with the in-memory one running the show. You definitely don't want to do pacman -Su before update-core since that will update everything in a fairly arbitrary order and you want to ensure the core is updated first (and the shell exited next) before updating any other packages.

`[2]` While installing the toolchain group or the gcc package will install exactly the same set of 16 package (use paman -Sg mingw-w64-x86_64-toolchain and pactree mingw-w64-x86_64-gcc to see the same lists), installing the toolchain groups is the correct procedure here since that's what you actually want to install. But the difference is pretty minor I'll admit!

Again, many thanks for this.

**Comment by FeodorFitsner** [comment]
Hm, when I did a fresh install of MSYS2 using the [installer](http://sourceforge.net/projects/msys2/files/Base/x86_64/msys2-x86_64-20150512.exe/download) `update-core` wasn't immediately available. Maybe it's just me - I'll try on a clean machine.

Regarding `mingw-w64-{x86_64,i686}-qt5` package - we have all recent Qt frameworks pre-installed in `C:\Qt`. Isn't the same?

**Comment by mingwandroid** [comment]
Ah .. it's part of more recent pacman packages than the last one we bundled into installers. Sorry about that.

One tip for finding where things live is to install and use pkgfile:

```
pacman -S pkgfile
pkgfile --update
pkgfile /usr/bin/update-core # (you need to know the full path and correct filename here)
```

The Qt5 packages you have already are probably mingw-w64 i686 (and MSVC) ones built by Qt-Project itself. They aren't built as part of the MSYS2 software distro and so won't use our shared libraries for its dependencies. Qt-Project builds usually prefer to statically link to their dependencies. They've also probably been built with GCC 4.8.x or 4.9.x and so aren't ABI compatible with GCC 5.2-built libraries (e.g. C++ small string optimization and probably more).

MSYS2 offers shared dependencies and binary compatibility between its' packages but can't make any guarantees for packages from others, so we discourage attempting to mix them (this isn't to say they can't co-exist happily on the same AppVeyor installations though!).

**Comment by ariscop** [comment]
I've been trying to install and use msys2
https://github.com/ariscop/elemental-ircd/blob/appveyor/appveyor.yml
But it takes a good 15 minutes to get everything installed, atop an already slow msys build it's impossible to compile that project on appveyor

**Comment by essen** [comment]
@ariscop I noticed on Monday that there is no a C:\msys64 folder with MSYS2 preinstalled. I could shorten my build steps to basically this: https://github.com/ninenines/erlang.mk/blob/master/appveyor.yml

As you can see I install strictly what's necessary for my project, and don't update the system itself (I only really need git and make). The pacman-mirrors is there only because I had issues with slow sourceforge otherwise also. You can probably shave off a few minutes.

(Didn't know about install step though, perhaps I should look into it. :-)

Off-topic:

I agree the time limit is really low though, I wish AppVeyor had limits similar to CircleCI (up to 2 hours per command and 4 or 5 hours total). I don't have that many PR/pushes so it's a shame I can't run extensive test suites.

**Comment by ariscop** [comment]
It's not the time limit, msys2 is just absurdly slow, combined with what i assume are cpu limits on appveyor.
same codebase builds in 2 minutes on travis

I'll try the existing msys install

**Comment by ariscop** [comment]
Using the existing install has solved my problem
msys2 isn't listed under [installed software](http://www.appveyor.com/docs/installed-software)

**Comment by FeodorFitsner** [comment]
Right. It's been just updated.
