### ISSUE TITLE
XCode 12, Xamarin.iOS 14

### ISSUE THREAD

**Issue by VladislavAntonyuk** [appveyor/ci#3542]
Please add support for XCode 12 and update Xamarin.iOS SDK to version 14

**Comment by cgutman** [comment]
It would be great to get Xcode 12 into the next image. I'm blocked from creating libraries for Apple Silicon Macs due to the lack of Xcode 12 in AppVeyor.

@FeodorFitsner Are you tracking the Xcode 12 work as part of #3212 (specifically the suggestion of "keep the latest stable / point release of each major Xcode release around")? If not, should this issue be added to the 'next-macos-images-update' milestone?

**Comment by HarelM** [comment]
Same here, but just for xcode.
I've just updated a Cordova plugin I use to the latest version to find out it can't be complied with xcode < 12, which is a real bummer... :-(
The reason for that can be seen here:
https://github.com/dooboolab/react-native-iap/issues/1204#issuecomment-748506202
This is not the plugin I use, I updated the plugin https://github.com/j3k0/cordova-plugin-purchase which seems to have updated the latest version to use capabilities of xcode 12, apparently...
I'll be downgrading the plugin until this is resolve, please keep me posted.
Thanks for all the hard work and the great service you give to our open source project!

**Comment by VladislavAntonyuk** [comment]
To be honest I am not using appveyor because it has poor updates compare to GitHub actions and Azure DevOps Pipelines

**Comment by FeodorFitsner** [comment]
XCode 12.3 has been added to `macos` image: https://www.appveyor.com/updates/2020/12/27/
