### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by treyhunner** [appveyor/ci#3741]
Python 3.10.0 was released today. 😊

Per #3541, it took 21 days for Python 3.9 support on AppVeyor and 28 days for Python 3.8 support.

**Comment by hugovk** [comment]
> Per #3541, it took 21 days for Python 3.9 support on AppVeyor and 28 days for Python 3.8 support.

Today is 21 day since Python 3.10 was released.

Any ETA on making 3.10 available? This is blocking some projects from releasing binary wheels for Windows, and they're considering migrating to other CI providers.

Thank you!

**Comment by bayasdev** [comment]
Just had to downgrade to Python 3.9.7 in order to continue working on a project with PostgresSQL databases, I hope the Windows binaries get ready for Python 3.10 soon.

**Comment by hugovk** [comment]
This was released yesterday, thank you!

* https://github.com/appveyor/website/commit/a07b8024908765ff48ddef38f9dd6d0a7238240a
* https://www.appveyor.com/updates/2021/11/02/

Remember to use the Visual Studio 2019 image (for example, `image: Visual Studio 2019`).

* https://www.appveyor.com/docs/windows-images-software/#python

28 days since Python 3.10 release, a week longer than for 3.9 and 3 days longer than for 3.8. Thanks again!
