### ISSUE TITLE
Msys2 unexpected exit code 254: c:\msys64\usr\bin\bash.exe --login -c exit

### ISSUE THREAD

**Issue by johncaliskan** [appveyor/ci#3777]
Does anyone know how to fix "unexpected exit code 254: c:\msys64\usr\bin\bash.exe --login -c exit" issue when installing msys2?
![Capture](https://user-images.githubusercontent.com/58123445/150658095-da1c3f4f-98e8-4713-997a-ff2e5cd7a24e.PNG)

**Comment by gxgl** [comment]
Hi,

same issue here and everything that I have found on the internet didn't help.

BR,
George

**Comment by gxgl** [comment]
what is curious, it started with new version of git and then I have tested with msys2 and cygwin, all of them, same issue, I also suspect my machine

**Comment by gxgl** [comment]
Hi,

it looks like this settings (Windows Security -> App & browser control -> Exploit protection  -> System settings)
![image](https://user-images.githubusercontent.com/11505258/153461844-a264068f-8acd-47e9-956e-a0ad4a054051.png)
must be off.

At least for me, this is the way that I fix the problem.

Now my question is: How and why this settings are blocking the apps? :)

BR,
George

**Comment by CPosingies** [comment]
Anybody an idea to handle this crap on a current Windows 11 ([Version 10.0.25267.1000)? The SEHOP stuff applied to Vista like aeons ago.

**Comment by som6one** [comment]
Just create folders:
 \windows\system32\drivers\etc
 \windows\system32\drivers\etc\hosts (or host - I am not sure)
 \windows\system32\drivers\etc\services
 \windows\system32\drivers\etc\networks
 \windows\system32\drivers\etc\protokol

**Comment by AngelTs** [comment]
Same issue. Nothing helps!

**Comment by kikonen** [comment]
So what is solution in windows 11?

i.e. getting
```
Error during installation process (com.msys2.root):
Execution failed (Unexpected exit code: 1): "C:/app/msys64\usr\bin\bash.exe --login -c exit"
```

**Comment by TinkerRnD** [comment]
> Does anyone know how to fix "unexpected exit code 254: c:\msys64\usr\bin\bash.exe --login -c exit" issue when installing msys2? ![Capture](https://user-images.githubusercontent.com/58123445/150658095-da1c3f4f-98e8-4713-997a-ff2e5cd7a24e.PNG)

Hello all, I do know of a solution that may help most of you. 

The problem stems from the ASLR features in windows. So instead of disabling ASLR system wide, we can work around this by disabling the "Mandatory ASLR" and the "BottumUp ASLR" security features located in: 

Windows Security > App & Browse control> Program Settings > + Add program to customize 

From here add all of the binaries in C:\msys64\usr\bin and disable those two features

Now this takes a lot of time so here is a script you can run that will do all of the work for you (depending on your installation path, you may need to update the location of your msys2): https://github.com/TinkerRnD/Helpful-Scripts/blob/main/Remove_ASLR.ps1

I have been able to fix all my windows shells this way (Cygwin, Git Bash and mys2). Hopefully not a permanent solution but will get you up and running until the next patch @msys2 ;)

**Comment by zericksp** [comment]
My case was solved disabling windows security -> ransomware protection -> controlled folder access.

**Comment by urmom123asd** [comment]
hello @TinkerRnD what do you mean by '' and disable those two features''
