### ISSUE TITLE
C:\MinGW\msys\1.0\bin\bash The system cannot find the path specified.

### ISSUE THREAD

**Issue by igsilya** [appveyor/ci#3893]
The builds started failing a few hours ago.  Visual Studio 2019 image seem to miss the msys installation:

```
C:\MinGW\msys\1.0\bin\bash -lc "echo \"C:/MinGW /mingw\" > /etc/fstab"
The system cannot find the path specified.
Command exited with code 1
```

Example: https://ci.appveyor.com/project/igsilya/ovs/build/job/1s49rn253o7apswo

**Comment by OwenMcDonnell** [comment]
I aborted an image update in progress to try to remedy this. Let me know if you are still seeing this failure.

**Comment by igsilya** [comment]
New builds are working now.  Thanks!
Will keep an eye on how they go.

**Comment by OwenMcDonnell** [comment]
Going to deploy a new image today that hopefully addresses the issue. Let me know if the issue recurs.

**Comment by OwenMcDonnell** [comment]
This should be fixed now on both `Visual Studio 2019` and `Visual Studio 2022` images.

**Comment by igsilya** [comment]
Can confirm, the builds are working fine for the last few days.  Thanks!

**Comment by igsilya** [comment]
Hi @OwenMcDonnell , we got this problem again today: https://ci.appveyor.com/project/blp/ovs/builds/48647442
Could you please take a look?

**Comment by OwenMcDonnell** [comment]
I Will be working on a fix for this in the coming days. In the meantime please use `Previous Visual Studio 2019` image.

**Comment by OwenMcDonnell** [comment]
@igsilya can you confirm this is working again with current image?

**Comment by igsilya** [comment]
@OwenMcDonnell , seems to be working so far: https://ci.appveyor.com/project/igsilya/ovs/builds/48705167

**Comment by OwenMcDonnell** [comment]
@igsilya Not sure if you're subscribed to Appveyor's technical newsletter or not, but with the [latest update](https://www.appveyor.com/updates/2023/12/03/) we've also announced the end of support for MinGW 32 bit v.5.3.0 at the next image update. At that time, you'll still be able to run builds with `Previous Visual Studio 2019` image, but that then will be replaced at the next image update. At which point you'll have to switch to MinGW-w64 and MSYS2 or else run your own script to install the, now very old, MinGW 32 bit. 
I'm not too familiar with development using these toolchains, but it seems that you may only need to update your builds to use `C:\msys64\usr\bin\bash` instead of `C:\MinGW\msys\1.0\bin\bash`.

**Comment by igsilya** [comment]
@OwenMcDonnell thanks for the heads up!  I'm not an expert in our windows build myself, but I know we link with some 32-bit libraries, so maybe some other adjustments will be needed.  We'll look into that.

Closing this issue for now as the new image appears to be working fine.  Thanks again!

**Comment by GitMensch** [comment]
Can you please also fix the VS 2022 image? It has the same issue (the C:\MinGW folder is empty).

Note: I don't see a reference in https://www.appveyor.com/updates/2023/12/03/ that MinGW is (to be) removed and https://www.appveyor.com/docs/windows-images-software/#mingw-msys-cygwin also list that to be available.

When it is removed: how long will it stay available in the "Previous" images (I _guess_ until the next update) and how long with the others (pre 2019)?
