### ISSUE TITLE
'cinst' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by hpwamr** [appveyor/ci#3923]
Hello,
We are using [AppVeyor to check the PR's](https://ci.appveyor.com/project/rizonesoft/notepad3/history) before merging them with [Notepad3-Master](https://github.com/rizonesoft/Notepad3).

#### The last successful check was June 1, 2024.
![Tests passed](https://github.com/appveyor/ci/assets/34211772/8a03281b-6412-42ea-a6fa-26d5808b5669)

#### But all checks from June 9, 2024 have failed.  😬 
![Tests failed](https://github.com/appveyor/ci/assets/34211772/e0500f9f-912f-473c-a1cb-7dc3a2105faf)

For our part, nothing has changed between these two dates! 👀 

Can you help us, please. 🤔

In .zip attachment our appveyor.yml file:  [appveyor.zip](https://github.com/user-attachments/files/15935872/appveyor.zip)

**Comment by gep13** [comment]
The AppVeyor build images recently updated the version of Chocolatey CLI that is installed by default, this was announced here:

https://www.appveyor.com/updates/2024/06/13/

and here:

https://www.appveyor.com/updates/2024/06/18/

Starting with Chocolatey CLI 2.0.0, the historical shims (for the likes of `cinst`, `cpush`, etc.) have been removed.  This was announced here:

https://docs.chocolatey.org/en-us/guides/upgrading-to-chocolatey-v2-v6/#chocolatey-shortcut-shims-removed

My recommendation would be to switch to using `choco install`, rather than `cinst`.

**Comment by hpwamr** [comment]
> My recommendation would be to switch to using `choco install`, rather than `cinst`.

Hello @gep13 ,
Your recommended fix works perfectly, this issue is resolved. 👍 

![Tests passed after fix](https://github.com/appveyor/ci/assets/34211772/5f1c8d15-478a-4eff-ba5c-223ea2871d70)

Thank you very much for your help.  😃
