### ISSUE TITLE
Qt 6.8

### ISSUE THREAD

**Issue by dismine** [appveyor/ci#3932]
https://www.qt.io/blog/qt-6.8-released

**Comment by BLumia** [comment]
Qt 6.8.1 is also available now.

By the way the current Qt version provided in appveyor's Windows image (Qt 6.7.2) is affected by [QTBUG-126775](https://bugreports.qt.io/browse/QTBUG-126775) (cause incorrect behavior with `windeployqt`), so if appveyor would like to keep providing 6.7, it's suggest to upgrade to 6.7.3 as well.

**Comment by novomesk** [comment]
AppVeyor has Qt 6.8.0 now, however I have trouble to build a package which worked previously with Qt 6.7.2

I got following error:
```
-- Could NOT find Qt6Core5Compat (missing: Qt6Core5Compat_DIR)
CMake Error at CMakeLists.txt:83 (find_package):
  Found package configuration file:
    C:/Qt/6.8.0/msvc2022_64/lib/cmake/Qt6/Qt6Config.cmake
  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:
  Failed to find required Qt component "Core5Compat".
  Expected Config file at
  "C:/Qt/6.8.0/msvc2022_64/lib/cmake/Qt6Core5Compat/Qt6Core5CompatConfig.cmake"
  does NOT exist
```

Qt 6.8.1 exists already. When I install it on my computer, I have there this file:
`C:\Qt\6.8.1\msvc2022_64\lib\cmake\Qt6Core5Compat\Qt6Core5CompatConfig.cmake`

I don't know why the `Qt6Core5CompatConfig.cmake` is not there in AppVeyor's Qt 6.8.0 .

I am suggesting to upgrade to Qt 6.8.1 anyway.

**Comment by BLumia** [comment]
By the way, the `mingw1310_64` toolchain also is missing which **seems** to be used by Qt 6.8's MinGW version.

**Comment by OwenMcDonnell** [comment]
Qt 6.8 has some more significant differences in terms of components and folder structure that weren't immediately apparent. New images with 6.8.1 will be coming that hopefully address these issue soon.

**Comment by OwenMcDonnell** [comment]
https://www.appveyor.com/updates/2024/12/28/

**Comment by bjorn** [comment]
@OwenMcDonnell Please note that the documentation at https://www.appveyor.com/docs/windows-images-software/#qt says that Qt 6.8.1 is installed at `C:\Qt\6.8.1\msvc2019_64`, but it actually is `C:\Qt\6.8.1\msvc2022_64`. Similarly, the ARM 64-bit version is at `msvc2022_arm64` rather than `msvc2019_arm64`.

(I haven't checked whether Visual Studio 2019 is actually still compatible, judging by the naming it might not be, in which case it would also not make sense to include Qt 6.8.1 in the Visual Studio 2019 image (except for the MinGW version))

**Comment by OwenMcDonnell** [comment]
@bjorn Yes,  there is a [PR](https://github.com/appveyor/website/pull/896) for that, though it looks like merging it got overlooked. Thanks for reminding.
