### ISSUE TITLE
ASP.NET and Web Tools 2015 (Beta7) for Visual Studio 2015

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#397]
Discussion: http://help.appveyor.com/discussions/questions/1633-install-latest-aspnet-5-tools-on-visual-studio-2015-image

Download URL: http://www.microsoft.com/en-us/download/details.aspx?id=48738
Test repo: https://github.com/FeodorFitsner/AppveyorAspNet5Build

**Comment by petrsvihlik** [comment]
+1 for this issue. 
I'm having [troubles](https://ci.appveyor.com/project/petrsvihlik/wopihost) with my appveyor build after upgrading to beta7.
There were some [breaking renames](https://github.com/aspnet/Announcements/issues/51) in beta7. Discussion are [here](https://github.com/aspnet/dnx/issues/2371) and [here](https://github.com/aspnet/Announcements/issues/44).
Hope you'll manage to update the tooling soon :)

**Comment by FeodorFitsner** [comment]
Btw, is this update backward compatible with beta6?

**Comment by jeffpapp** [comment]
> Btw, is this update backward compatible with beta6?

I just tested this against beta6 code and it still works with the beta7 tooling installed on the build worker

https://ci.appveyor.com/project/Squarei/appveyoraspnet5build/build/1.0.7

**Comment by petrsvihlik** [comment]
Cool. Even if it didn't I still think it's best to stick with the latest version (when talking about betas).

**Comment by FeodorFitsner** [comment]
Great, thanks for looking into that.

**Comment by Daniel15** [comment]
+1 - I think I'm encountering issues due to https://github.com/aspnet/Announcements/issues/44. I have a build that did work on AppVeyor with beta6, but since I upgraded it to beta7 it's failing with "System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies. The system cannot find the file specified.". I think upgrading to the latest tools version will fix it.
