### ISSUE TITLE
Overwrite assets in GitHub deployment provider

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#480]
Discussion: http://stackoverflow.com/questions/33503045/force-deploy-on-github-from-appveyor

**Comment by malaterre** [comment]
Thanks much for logging this as bug. Do you have a suggestion to manually delete a draft/prerelease (eg. using curl) ?

**Comment by FeodorFitsner** [comment]
Yes, you can [list all release assets](https://developer.github.com/v3/repos/releases/#list-assets-for-a-release) and then [delete](https://developer.github.com/v3/repos/releases/#delete-a-release-asset) them one-by-one. There are examples of how to use curl: https://developer.github.com/v3/ For authentication you can generate [personal access token](https://help.github.com/articles/creating-an-access-token-for-command-line-use/).

**Comment by malaterre** [comment]
That's odd this is still failing for me:

https://ci.appveyor.com/project/malaterre/gdcm/build/2.7.0.184/job/ho0kubxn04miao78

```
Creating "v2.7.0" release for repository "malaterre/GDCM" tag "v2.7.0" commit "f3571c4e7063b2a9b3ce2526a59a14ba8942e75b"...Skipped (Release with tag "v2.7.0" already exists)
Deleting existing release asset "GDCM-2.7.0-Windows-x86.exe"...OK
Uploading "GDCM-2.7.0-Windows-x86.exe" to release assets...OK
Deleting existing release asset "GDCM-2.7.0-Windows-x86.zip"...OK
Uploading "GDCM-2.7.0-Windows-x86.zip" to release assets...Error uploading release asset: 502 - Bad Gateway
```

**Comment by FeodorFitsner** [comment]
That was an error from GitHub, kind of sporadic error - I've seen that before.

**Comment by cyberium** [comment]
Hi,
So in appveyor.yml itself there is no way to force recreate/update a release tag?

To be more cleare here is what iam trying to do.
At every commit to my repo i need to let appveyor try to compile the code and then create a snapshot in github release section.
If i keep same name for the tag it will not be recreated (skip because already exist)
The files are correctly updated but the name/date and link to the commit are thus wrong.
It will be nice to have in appveyor itself a simple bool to say that we want to recreate the tag if exist.

**Comment by FeodorFitsner** [comment]
I've added a new issue: https://github.com/appveyor/ci/issues/680
