### ISSUE TITLE
WDK 10

### ISSUE THREAD

**Issue by Liryna** [appveyor/ci#589]
Since I have retarget my project to the new sdk (vs 2015 update 1), I have `fatal error C1083: Cannot open include file: 'ntifs.h': No such file or directory` (WDK include file)
https://ci.appveyor.com/project/Maxhy/dokany/build/0.8.0-295/job/r9c93wclbiqgjqm6

I am unable to reproduced this error on my environement.
Does the last WDK 10 is installed ? (10.0.10586.0)

Download URL:
https://msdn.microsoft.com/en-us/windows/hardware/dn913721.aspx

    ren 'C:\Program Files (x86)\Windows Kits\10\include\wdf' '00wdf'

**Comment by FeodorFitsner** [comment]
What should be the location of that include file?





On Tue, Dec 29, 2015 at 7:58 AM -0800, "Liryna" <notifications@github.com> wrote:












Since I have retarget my project to the new sdk (vs 2015 update 1), I have fatal error C1083: Cannot open include file: 'ntifs.h': No such file or directory (WDK include file)

https://ci.appveyor.com/project/Maxhy/dokany/build/0.8.0-295/job/r9c93wclbiqgjqm6



I am unable to reproduced this error on my environement.

Does the last WDK 10 is installed ?

**Comment by Liryna** [comment]
Path: `c:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\km\ntifs.h`

**Comment by FeodorFitsner** [comment]
Thanks. Apparently, WDK 10 is not installed on build workers. Will install it this week.
