### ISSUE TITLE
kernel32.lib not found in 64-bit build

### ISSUE THREAD

**Issue by c-lipka** [appveyor/ci#598]
Can someone please have a look at what's going on here?

https://ci.appveyor.com/project/c-lipka/povray/build/job/ycsnd35f2ev5tlh4

What I'm noticing is that the output of `devenv windows\vs10\povray.sln /upgrade` has become much less verbose compared to the last successful build (https://ci.appveyor.com/project/c-lipka/povray/build/3.7+av72/job/43v21rlramklhkxi), and that the error message is identical to what I was seeing earlier when I tried to build the 64-bit version from the VS 2010 project files without prior conversion to VS 2015 (e.g https://ci.appveyor.com/project/c-lipka/povray/build/3.7.1-alpha.8353331.18/job/a2hsbh87ncyv7ph9).

**Comment by FeodorFitsner** [comment]
Well, since that last successful build 2 months ago there was a number of environment updates (http://www.appveyor.com/updates). Definitely, something could have been affected by any update.

You can troubleshooting this by using RDP: http://www.appveyor.com/docs/how-to/rdp-to-build-worker

I've found some links that might be related to the issue: http://www.mathworks.com/matlabcentral/answers/62285-lnk1181-cannot-open-input-file-kernel32-lib
https://github.com/nodejs/node-gyp/wiki/Visual-Studio-2010-Setup

**Comment by c-lipka** [comment]
Thanks, the RDP connection really simplified digging into this.

Looks like "devenv /upgrade" no longer adds "PlatformToolset" properties to the project files (maybe a change introcuded with Update 1 of VS 2015?); explicitly specifying an environment variable `PlatformToolset` in the build environment and setting it equal to `v140` seems to solve the problem.
