### ISSUE TITLE
Expand environment variables in build cache entries

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#76]
Discussion: http://help.appveyor.com/discussions/problems/1163-unable-to-use-env-var-in-build-cache-config

Example in appveyor.yml:

```
cache: 
    - '%CYG_CACHE%' 
    - '%HAXELIB_ROOT%'
```

**Comment by vitaly-krugl** [comment]
@FeodorFitsner, whatever happened to this? I was hoping to be able to use environment variables from the `environment:` block in appveyor.yml for the usual reasons that one would use a name constant in a program instead of using the value verbatim all over the place. However, this doesn't seem to work. It would be great if it did.

**Comment by FeodorFitsner** [comment]
What did work for you?

It could be like that, for example:

```
cache:
- '%LocalAppData%\NuGet\Cache -> **\packages.config'
```

**Comment by vitaly-krugl** [comment]
@FeodorFitsner: I defined some variables in `matrix:` under `environment:`, and wanted to use them in `cache:`.

**Comment by FeodorFitsner** [comment]
That should be possible as environment variables are being set before cache restore.

**Comment by vitaly-krugl** [comment]
Hmmm..., perhaps my build cache settings didn't have the desired effect since PRs were being built.

**Comment by vitaly-krugl** [comment]
Thank you @FeodorFitsner, after merging the PR, I was able to confirm that this works.
