### ISSUE TITLE
Cancel pending builds of closed PRs

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/ci#77]
Discussion: http://help.appveyor.com/discussions/suggestions/483-closed-prs

**Comment by ricardopolo** [comment]
:+1:

**Comment by tkelman** [comment]
It's quite surprising that this now results in cancelling of an in-progress running build for a PR when it gets merged. I'd rather let it finish if it's already started.

**Comment by FeodorFitsner** [comment]
Yeah, may need to revise this feature.

**Comment by lamont-granquist** [comment]
Yeah wound up here because in-progress running builds getting cancelled and failing is not the behavior that I want.

The workflow here is that I've got a PR that needs a rebase and a CHANGELOG.md update but should pass.  So I do that and force push the branch, which kicks off a new test run.  I'd like the test run to complete and the PR to go green just as validation that I did my work correctly, but I don't want to wait for the builds to complete before I can press merge.  If I have to wait for them, I may forget, and its likely that some other merge will merge-conflict on my CHANGELOG.md update.  So I press merge to get my changes into master and then appveyor fails and the PR goes red.
