### ISSUE TITLE
Previously successful builds with Python 3.5 now failing

### ISSUE THREAD

**Issue by nemequ** [appveyor/ci#963]
https://ci.appveyor.com/project/quixdb/brotli/build/1.0.25 was successful when it was built 6 days ago (see google/brotli#400).  I just rebuilt it and it failed.

**Comment by FeodorFitsner** [comment]
Build worker image has not been changed since the last successful build.

There is `setuptools` external dependency that was changed between last successful and failing builds.

Successful build uses v25.1.1: https://ci.appveyor.com/project/quixdb/brotli/build/1.0.22/job/yi3ik4s263ry5209#L31
All failed builds use v25.1.4: https://ci.appveyor.com/project/quixdb/brotli/build/1.0.23/job/3elr46palt9079ub#L31

Downgrading `setuptools` version to 25.1.1 fixes build: https://github.com/FeodorFitsner/brotli/blob/master/appveyor.yml#L31

Build results: https://ci.appveyor.com/project/FeodorFitsner/brotli

**Comment by FeodorFitsner** [comment]
Updates to build worker images: http://www.appveyor.com/updates

**Comment by nemequ** [comment]
@FeodorFitsner thanks.  We've been in touch with the setuptools people, and the latest release (25.1.6) seems to fix the issue.
